# Generated by Django 6.0 on 2025-12-28 08:28

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact_management", "0002_initial"),
        ("lead_management", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("shared_with_team", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Enrollment"),
                            ("lead_score", "Lead Score Threshold"),
                            ("stage_change", "Deal Stage Change"),
                            ("form_submission", "Form Submission"),
                            ("page_visit", "Website Page Visit"),
                            ("inactivity", "Inactivity Period"),
                            ("tag_added", "Tag Added"),
                            ("custom_event", "Custom Event"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                (
                    "trigger_config",
                    models.JSONField(
                        default=dict, help_text="Trigger-specific configuration"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        default=dict,
                        help_text="Sequence settings like send window, timezone",
                    ),
                ),
                (
                    "exit_conditions",
                    models.JSONField(
                        default=dict, help_text="Conditions to auto-remove contacts"
                    ),
                ),
                ("personalization_enabled", models.BooleanField(default=True)),
                ("ai_optimization_enabled", models.BooleanField(default=True)),
                ("total_enrolled", models.IntegerField(default=0)),
                ("total_completed", models.IntegerField(default=0)),
                ("total_converted", models.IntegerField(default=0)),
                (
                    "avg_open_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_click_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_reply_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activated_at", models.DateTimeField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_email_sequences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "automation_email_sequences",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomatedTrigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("lead_score", "Lead Score Threshold"),
                            ("stage_change", "Deal Stage Change"),
                            ("inactivity", "Contact Inactivity"),
                            ("form_submission", "Form Submission"),
                            ("page_visit", "Website Page Visit"),
                            ("email_event", "Email Event"),
                            ("tag_change", "Tag Added/Removed"),
                            ("field_change", "Field Value Change"),
                            ("date_based", "Date-based Trigger"),
                            ("api_event", "API Event"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "trigger_config",
                    models.JSONField(
                        default=dict, help_text="Trigger-specific configuration"
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=list, help_text="Additional conditions to evaluate"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("prevent_re_enrollment", models.BooleanField(default=True)),
                ("total_triggered", models.IntegerField(default=0)),
                ("total_enrolled", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_triggered_at", models.DateTimeField(blank=True)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="email_sequence_automation.emailsequence",
                    ),
                ),
            ],
            options={
                "db_table": "email_automated_triggers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SequenceAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("new_enrollments", models.IntegerField(default=0)),
                ("active_enrollments", models.IntegerField(default=0)),
                ("completed_enrollments", models.IntegerField(default=0)),
                ("exited_enrollments", models.IntegerField(default=0)),
                ("emails_sent", models.IntegerField(default=0)),
                ("emails_delivered", models.IntegerField(default=0)),
                ("emails_opened", models.IntegerField(default=0)),
                ("emails_clicked", models.IntegerField(default=0)),
                ("emails_replied", models.IntegerField(default=0)),
                ("emails_bounced", models.IntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                (
                    "conversion_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "open_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "click_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "reply_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "bounce_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="email_sequence_automation.emailsequence",
                    ),
                ),
            ],
            options={
                "db_table": "email_sequence_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SequenceStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("email", "Send Email"),
                            ("wait", "Wait Period"),
                            ("condition", "Conditional Branch"),
                            ("task", "Create Task"),
                            ("update_field", "Update Contact Field"),
                            ("add_tag", "Add Tag"),
                            ("remove_tag", "Remove Tag"),
                            ("notify", "Notify Team Member"),
                            ("webhook", "Call Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("wait_days", models.IntegerField(default=0)),
                ("wait_hours", models.IntegerField(default=0)),
                ("wait_minutes", models.IntegerField(default=0)),
                (
                    "condition_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email_opened", "Email Opened"),
                            ("email_clicked", "Email Clicked"),
                            ("email_replied", "Email Replied"),
                            ("lead_score_above", "Lead Score Above"),
                            ("lead_score_below", "Lead Score Below"),
                            ("has_tag", "Has Tag"),
                            ("field_equals", "Field Equals"),
                            ("visited_page", "Visited Page"),
                        ],
                        max_length=30,
                    ),
                ),
                ("condition_config", models.JSONField(default=dict)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Type-specific configuration"
                    ),
                ),
                ("ab_test_enabled", models.BooleanField(default=False)),
                ("total_executed", models.IntegerField(default=0)),
                ("total_completed", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch_no_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="no_branches",
                        to="email_sequence_automation.sequencestep",
                    ),
                ),
                (
                    "branch_yes_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="yes_branches",
                        to="email_sequence_automation.sequencestep",
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="email_sequence_automation.emailsequence",
                    ),
                ),
            ],
            options={
                "db_table": "email_sequence_steps",
                "ordering": ["sequence", "step_number"],
            },
        ),
        migrations.CreateModel(
            name="SequenceEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("converted", "Converted"),
                            ("unsubscribed", "Unsubscribed"),
                            ("bounced", "Bounced"),
                            ("exited", "Exited (Condition Met)"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("next_action_at", models.DateTimeField(blank=True)),
                ("enrollment_trigger", models.CharField(blank=True, max_length=100)),
                ("exit_reason", models.CharField(blank=True, max_length=200)),
                ("exited_at", models.DateTimeField(blank=True)),
                ("emails_sent", models.IntegerField(default=0)),
                ("emails_opened", models.IntegerField(default=0)),
                ("emails_clicked", models.IntegerField(default=0)),
                ("emails_replied", models.IntegerField(default=0)),
                ("personalization_data", models.JSONField(default=dict)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_sequence_enrollments",
                        to="contact_management.contact",
                    ),
                ),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sequence_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequence_enrollments",
                        to="lead_management.lead",
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="email_sequence_automation.emailsequence",
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_enrollments",
                        to="email_sequence_automation.sequencestep",
                    ),
                ),
            ],
            options={
                "db_table": "email_sequence_enrollments",
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="SequenceEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("preview_text", models.CharField(blank=True, max_length=300)),
                ("body_html", models.TextField()),
                ("body_text", models.TextField(blank=True)),
                ("ai_generated", models.BooleanField(default=False)),
                (
                    "ai_prompt",
                    models.TextField(
                        blank=True, help_text="Prompt used to generate this email"
                    ),
                ),
                (
                    "ai_context",
                    models.JSONField(
                        default=dict, help_text="Context data for AI generation"
                    ),
                ),
                ("variant_name", models.CharField(default="A", max_length=50)),
                (
                    "variant_weight",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_winner", models.BooleanField(default=False)),
                (
                    "personalization_tokens",
                    models.JSONField(
                        default=list, help_text="Dynamic tokens used in email"
                    ),
                ),
                ("total_sent", models.IntegerField(default=0)),
                ("total_delivered", models.IntegerField(default=0)),
                ("total_opened", models.IntegerField(default=0)),
                ("total_clicked", models.IntegerField(default=0)),
                ("total_replied", models.IntegerField(default=0)),
                ("total_bounced", models.IntegerField(default=0)),
                ("total_unsubscribed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="email_sequence_automation.sequencestep",
                    ),
                ),
            ],
            options={
                "db_table": "email_sequence_emails",
                "ordering": ["step", "variant_name"],
            },
        ),
        migrations.CreateModel(
            name="SequenceActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("step_started", "Step Started"),
                            ("email_sent", "Email Sent"),
                            ("email_opened", "Email Opened"),
                            ("email_clicked", "Email Clicked"),
                            ("email_replied", "Email Replied"),
                            ("email_bounced", "Email Bounced"),
                            ("condition_evaluated", "Condition Evaluated"),
                            ("branched", "Branched"),
                            ("task_created", "Task Created"),
                            ("field_updated", "Field Updated"),
                            ("tag_added", "Tag Added"),
                            ("tag_removed", "Tag Removed"),
                            ("paused", "Paused"),
                            ("resumed", "Resumed"),
                            ("completed", "Completed"),
                            ("exited", "Exited"),
                            ("error", "Error Occurred"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="email_sequence_automation.sequenceenrollment",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="email_sequence_automation.sequencestep",
                    ),
                ),
            ],
            options={
                "db_table": "email_sequence_activities",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ABTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "test_metric",
                    models.CharField(
                        choices=[
                            ("open_rate", "Open Rate"),
                            ("click_rate", "Click Rate"),
                            ("reply_rate", "Reply Rate"),
                            ("conversion_rate", "Conversion Rate"),
                        ],
                        default="open_rate",
                        max_length=20,
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        default=100,
                        help_text="Number of contacts before determining winner",
                    ),
                ),
                (
                    "confidence_level",
                    models.DecimalField(decimal_places=2, default=95.0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("winner_selected", "Winner Selected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("winner_selected_at", models.DateTimeField(blank=True)),
                ("auto_select_winner", models.BooleanField(default=True)),
                (
                    "results",
                    models.JSONField(
                        default=dict, help_text="Statistical test results"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "winning_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_tests",
                        to="email_sequence_automation.sequenceemail",
                    ),
                ),
                (
                    "step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ab_test",
                        to="email_sequence_automation.sequencestep",
                    ),
                ),
            ],
            options={
                "db_table": "email_sequence_ab_tests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailPersonalizationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("contact_field", "Contact Field"),
                            ("company_field", "Company Field"),
                            ("deal_field", "Deal Field"),
                            ("dynamic", "Dynamic Calculation"),
                            ("ai_generated", "AI Generated"),
                            ("custom", "Custom Value"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_field", models.CharField(blank=True, max_length=200)),
                ("default_value", models.CharField(blank=True, max_length=500)),
                (
                    "formula",
                    models.TextField(
                        blank=True, help_text="Formula for dynamic tokens"
                    ),
                ),
                (
                    "ai_prompt",
                    models.TextField(
                        blank=True, help_text="Prompt for AI-generated tokens"
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalization_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_personalization_tokens",
                "ordering": ["name"],
                "unique_together": {("owner", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="emailsequence",
            index=models.Index(
                fields=["owner", "status"], name="automation__owner_i_b8e45c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailsequence",
            index=models.Index(
                fields=["status", "-created_at"], name="automation__status_2362c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automatedtrigger",
            index=models.Index(
                fields=["trigger_type", "is_active"],
                name="email_autom_trigger_195d59_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sequenceanalytics",
            index=models.Index(
                fields=["sequence", "-date"], name="email_seque_sequenc_50c58b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sequenceanalytics",
            unique_together={("sequence", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="sequencestep",
            unique_together={("sequence", "step_number")},
        ),
        migrations.AddIndex(
            model_name="sequenceenrollment",
            index=models.Index(
                fields=["sequence", "status"], name="email_seque_sequenc_037b3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sequenceenrollment",
            index=models.Index(
                fields=["contact", "status"], name="email_seque_contact_db790e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sequenceenrollment",
            index=models.Index(
                fields=["next_action_at", "status"],
                name="email_seque_next_ac_610615_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sequenceenrollment",
            unique_together={("sequence", "contact")},
        ),
        migrations.AddIndex(
            model_name="sequenceactivity",
            index=models.Index(
                fields=["enrollment", "-timestamp"],
                name="email_seque_enrollm_ec6714_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sequenceactivity",
            index=models.Index(
                fields=["activity_type", "-timestamp"],
                name="email_seque_activit_a30f14_idx",
            ),
        ),
    ]
