# Generated by Django 6.0 on 2025-12-28 08:28

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lead_management", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillCertification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "skill_type",
                    models.CharField(
                        choices=[
                            ("product", "Product Knowledge"),
                            ("industry", "Industry Expertise"),
                            ("technical", "Technical Skill"),
                            ("language", "Language"),
                            ("certification", "Certification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "routing_weight",
                    models.IntegerField(
                        default=10, help_text="Importance in routing decisions"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "skill_certifications",
                "ordering": ["skill_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="EscalationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("lead_score", "Lead Score Threshold"),
                            ("no_response", "No Response"),
                            ("deal_size", "Deal Size"),
                            ("vip_customer", "VIP Customer"),
                            ("time_sensitive", "Time Sensitive"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trigger_config", models.JSONField(default=dict)),
                (
                    "escalate_to_manager",
                    models.BooleanField(
                        default=False, help_text="Escalate to assigned rep's manager"
                    ),
                ),
                ("notify_original_rep", models.BooleanField(default=True)),
                ("notify_manager", models.BooleanField(default=True)),
                (
                    "wait_hours",
                    models.IntegerField(
                        default=24, help_text="Hours before escalation"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=5)),
                ("total_escalations", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "escalate_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lead_escalation_rules",
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="LeadQualityScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "fit_score",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="ICP fit", max_digits=5
                    ),
                ),
                (
                    "engagement_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "intent_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "timing_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("scoring_factors", models.JSONField(default=dict)),
                ("recommended_rep_ids", models.JSONField(default=list)),
                ("recommended_rule_id", models.UUIDField(blank=True)),
                ("priority_tier", models.CharField(default="standard", max_length=20)),
                ("model_version", models.CharField(max_length=50)),
                ("scored_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_score",
                        to="lead_management.lead",
                    ),
                ),
            ],
            options={
                "db_table": "lead_quality_scores",
            },
        ),
        migrations.CreateModel(
            name="RebalancingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger_reason",
                    models.CharField(
                        choices=[
                            ("overload", "Rep Overloaded"),
                            ("underperformance", "Underperformance"),
                            ("availability", "Availability Change"),
                            ("manual", "Manual Rebalance"),
                            ("scheduled", "Scheduled Rebalance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("leads_moved", models.IntegerField(default=0)),
                (
                    "movements",
                    models.JSONField(default=list, help_text="List of lead movements"),
                ),
                ("before_distribution", models.JSONField(default=dict)),
                ("after_distribution", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True)),
                (
                    "affected_reps",
                    models.ManyToManyField(
                        related_name="rebalancing_events", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lead_rebalancing_events",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="RoutingAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_leads_routed", models.IntegerField(default=0)),
                ("auto_routed", models.IntegerField(default=0)),
                ("manual_routed", models.IntegerField(default=0)),
                ("escalations", models.IntegerField(default=0)),
                ("rebalanced", models.IntegerField(default=0)),
                (
                    "avg_match_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("avg_response_time_minutes", models.IntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("routing_by_method", models.JSONField(default=dict)),
                ("routing_by_rule", models.JSONField(default=dict)),
                ("rep_distribution", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "lead_routing_analytics",
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="RoutingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("round_robin", "Round Robin"),
                            ("skill_based", "Skill Based"),
                            ("territory", "Territory Based"),
                            ("performance", "Performance Based"),
                            ("custom", "Custom Logic"),
                        ],
                        default="round_robin",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Highest"),
                            (2, "High"),
                            (3, "Medium"),
                            (4, "Low"),
                            (5, "Lowest"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(default=dict, help_text="Criteria to match leads"),
                ),
                (
                    "target_teams",
                    models.JSONField(default=list, help_text="Team IDs to route to"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("respect_capacity", models.BooleanField(default=True)),
                ("consider_availability", models.BooleanField(default=True)),
                ("total_matches", models.IntegerField(default=0)),
                ("total_assignments", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fallback_rep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fallback_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_reps",
                    models.ManyToManyField(
                        blank=True,
                        related_name="routing_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lead_routing_rules",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesRepProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("max_leads_per_day", models.IntegerField(default=10)),
                ("max_active_leads", models.IntegerField(default=50)),
                ("current_lead_count", models.IntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "availability_schedule",
                    models.JSONField(
                        default=dict, help_text="Weekly availability schedule"
                    ),
                ),
                (
                    "industries",
                    models.JSONField(
                        default=list, help_text="Industries rep specializes in"
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(default=list, help_text="Relevant certifications"),
                ),
                (
                    "languages",
                    models.JSONField(default=list, help_text="Languages spoken"),
                ),
                (
                    "expertise_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "regions",
                    models.JSONField(
                        default=list, help_text="Geographic regions covered"
                    ),
                ),
                (
                    "countries",
                    models.JSONField(default=list, help_text="Countries covered"),
                ),
                (
                    "timezones",
                    models.JSONField(
                        default=list, help_text="Timezones rep can work in"
                    ),
                ),
                (
                    "min_deal_size",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "max_deal_size",
                    models.DecimalField(
                        decimal_places=2, default=1000000, max_digits=12
                    ),
                ),
                (
                    "preferred_deal_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12
                    ),
                ),
                ("total_leads_assigned", models.IntegerField(default=0)),
                ("total_leads_converted", models.IntegerField(default=0)),
                (
                    "avg_conversion_time_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "win_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_deal_size",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "response_time_minutes",
                    models.IntegerField(default=0, help_text="Average response time"),
                ),
                (
                    "customer_satisfaction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="0-5 rating",
                        max_digits=3,
                    ),
                ),
                (
                    "overall_performance_score",
                    models.DecimalField(decimal_places=2, default=50, max_digits=5),
                ),
                (
                    "last_performance_update",
                    models.DateTimeField(blank=True),
                ),
                ("last_assignment_at", models.DateTimeField(blank=True)),
                (
                    "assignment_weight",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_rep_profiles",
                "ordering": ["-overall_performance_score"],
            },
        ),
        migrations.CreateModel(
            name="TerritoryDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("countries", models.JSONField(default=list)),
                ("states", models.JSONField(default=list)),
                ("cities", models.JSONField(default=list)),
                ("postal_codes", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backup_reps",
                    models.ManyToManyField(
                        blank=True,
                        related_name="backup_territories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_rep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_territories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "territory_definitions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LeadAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assignment_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("round_robin", "Round Robin"),
                            ("skill_match", "Skill Match"),
                            ("ai_routing", "AI Routing"),
                            ("territory", "Territory"),
                            ("auto_escalation", "Auto Escalation"),
                            ("rebalancing", "Rebalancing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "match_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="AI match score 0-100",
                        max_digits=5,
                    ),
                ),
                (
                    "match_factors",
                    models.JSONField(
                        default=dict, help_text="Factors contributing to match"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("reassigned", "Reassigned"),
                            ("escalated", "Escalated"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("status_reason", models.CharField(blank=True, max_length=200)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True)),
                ("first_response_at", models.DateTimeField(blank=True)),
                ("outcome", models.CharField(blank=True, max_length=50)),
                ("outcome_at", models.DateTimeField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="made_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="lead_management.lead",
                    ),
                ),
                (
                    "previous_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routing_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="predictive_lead_routing.routingrule",
                    ),
                ),
            ],
            options={
                "db_table": "lead_assignments",
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "-assigned_at"],
                        name="lead_assign_lead_id_9bfb9f_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="lead_assign_assigne_f72168_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RepSkillAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "proficiency_level",
                    models.IntegerField(
                        choices=[
                            (1, "Basic"),
                            (2, "Intermediate"),
                            (3, "Advanced"),
                            (4, "Expert"),
                        ],
                        default=2,
                    ),
                ),
                ("certified_date", models.DateField(blank=True)),
                ("expiry_date", models.DateField(blank=True)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_assignments",
                        to="predictive_lead_routing.salesrepprofile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rep_assignments",
                        to="predictive_lead_routing.skillcertification",
                    ),
                ),
            ],
            options={
                "db_table": "rep_skill_assignments",
                "unique_together": {("rep", "skill")},
            },
        ),
    ]
