# Generated by Django 6.0 on 2025-12-28 08:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact_management", "0002_initial"),
        ("lead_management", "0002_initial"),
        ("opportunity_management", "0002_initial"),
        ("smart_scheduling", "0001_initial"),
        ("task_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#6B7280", max_length=7)),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="Keywords for auto-classification"
                    ),
                ),
                ("recording_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="voice_intelligence.conversationcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Conversation Categories",
                "db_table": "conversation_categories",
            },
        ),
        migrations.CreateModel(
            name="TranscriptionSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preferred_provider",
                    models.CharField(default="whisper", max_length=20),
                ),
                ("default_language", models.CharField(default="en", max_length=10)),
                ("auto_detect_language", models.BooleanField(default=True)),
                ("enable_speaker_diarization", models.BooleanField(default=True)),
                ("enable_punctuation", models.BooleanField(default=True)),
                ("enable_profanity_filter", models.BooleanField(default=False)),
                ("auto_generate_summary", models.BooleanField(default=True)),
                ("auto_extract_action_items", models.BooleanField(default=True)),
                ("auto_analyze_sentiment", models.BooleanField(default=True)),
                ("auto_score_calls", models.BooleanField(default=True)),
                ("notify_on_completion", models.BooleanField(default=True)),
                ("notify_on_high_priority_action", models.BooleanField(default=True)),
                (
                    "custom_vocabulary",
                    models.JSONField(default=list, help_text="Industry-specific terms"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcription_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transcription_settings",
            },
        ),
        migrations.CreateModel(
            name="VoiceNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audio_url", models.URLField(blank=True)),
                ("audio_path", models.CharField(blank=True, max_length=500)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("transcript", models.TextField(blank=True)),
                ("is_transcribed", models.BooleanField(default=False)),
                ("ai_title", models.CharField(blank=True, max_length=200)),
                ("ai_summary", models.TextField(blank=True)),
                ("action_items_extracted", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_notes",
                        to="contact_management.contact",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_notes",
                        to="lead_management.lead",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_notes",
                        to="opportunity_management.opportunity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "voice_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=300)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("phone_call", "Phone Call"),
                            ("video_meeting", "Video Meeting"),
                            ("voice_note", "Voice Note"),
                            ("upload", "Uploaded Recording"),
                            ("live_capture", "Live Capture"),
                        ],
                        default="phone_call",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("transcribing", "Transcribing"),
                            ("transcribed", "Transcribed"),
                            ("analyzing", "Analyzing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(blank=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("file_format", models.CharField(blank=True, max_length=20)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("sample_rate", models.IntegerField(blank=True, null=True)),
                ("channels", models.IntegerField(default=1)),
                ("bitrate", models.IntegerField(blank=True, null=True)),
                (
                    "participants",
                    models.JSONField(default=list, help_text="List of participants"),
                ),
                ("participant_count", models.IntegerField(default=2)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("detected_language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_recordings",
                        to="contact_management.contact",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_recordings",
                        to="lead_management.lead",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_recordings",
                        to="smart_scheduling.meeting",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_recordings",
                        to="opportunity_management.opportunity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "voice_recordings",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="Transcription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_text", models.TextField(blank=True)),
                (
                    "words_with_timing",
                    models.JSONField(
                        default=list, help_text="Words with start/end timestamps"
                    ),
                ),
                ("has_speaker_labels", models.BooleanField(default=False)),
                (
                    "speaker_segments",
                    models.JSONField(default=list, help_text="Segments by speaker"),
                ),
                ("speaker_count", models.IntegerField(blank=True, null=True)),
                (
                    "speaker_mapping",
                    models.JSONField(
                        default=dict, help_text="Speaker ID to name mapping"
                    ),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("word_error_rate", models.FloatField(blank=True, null=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("whisper", "OpenAI Whisper"),
                            ("google", "Google Speech-to-Text"),
                            ("aws", "AWS Transcribe"),
                            ("azure", "Azure Speech"),
                            ("deepgram", "Deepgram"),
                            ("assembly", "AssemblyAI"),
                            ("internal", "Internal"),
                        ],
                        default="whisper",
                        max_length=20,
                    ),
                ),
                ("provider_job_id", models.CharField(blank=True, max_length=200)),
                ("detected_language", models.CharField(default="en", max_length=10)),
                ("processing_time_seconds", models.FloatField(blank=True, null=True)),
                ("was_edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_transcriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recording",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcription",
                        to="voice_intelligence.voicerecording",
                    ),
                ),
            ],
            options={
                "db_table": "transcriptions",
            },
        ),
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_sentiment",
                    models.CharField(
                        choices=[
                            ("very_negative", "Very Negative"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                            ("positive", "Positive"),
                            ("very_positive", "Very Positive"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(default=0.0, help_text="-1 to 1 scale"),
                ),
                (
                    "sentiment_timeline",
                    models.JSONField(
                        default=list, help_text="Sentiment scores at intervals"
                    ),
                ),
                ("sentiment_by_speaker", models.JSONField(default=dict)),
                (
                    "emotions_detected",
                    models.JSONField(
                        default=dict, help_text="Emotion -> confidence mapping"
                    ),
                ),
                ("dominant_emotion", models.CharField(blank=True, max_length=50)),
                ("customer_sentiment", models.FloatField(blank=True, null=True)),
                ("agent_sentiment", models.FloatField(blank=True, null=True)),
                (
                    "positive_moments",
                    models.JSONField(
                        default=list, help_text="Timestamps of positive moments"
                    ),
                ),
                (
                    "negative_moments",
                    models.JSONField(
                        default=list, help_text="Timestamps of negative moments"
                    ),
                ),
                ("engagement_score", models.FloatField(blank=True, null=True)),
                (
                    "talk_ratio",
                    models.JSONField(
                        default=dict, help_text="Talk time by participant"
                    ),
                ),
                ("tone_analysis", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recording",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_analysis",
                        to="voice_intelligence.voicerecording",
                    ),
                ),
            ],
            options={
                "db_table": "sentiment_analyses",
            },
        ),
        migrations.CreateModel(
            name="KeyMoment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "moment_type",
                    models.CharField(
                        choices=[
                            ("objection", "Objection"),
                            ("agreement", "Agreement"),
                            ("question", "Question"),
                            ("commitment", "Commitment"),
                            ("concern", "Concern"),
                            ("interest", "Interest Shown"),
                            ("pricing", "Pricing Discussion"),
                            ("competitor", "Competitor Mention"),
                            ("next_step", "Next Step"),
                            ("highlight", "Highlight"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "start_timestamp",
                    models.IntegerField(help_text="Seconds from start"),
                ),
                ("end_timestamp", models.IntegerField(help_text="Seconds from start")),
                ("transcript_excerpt", models.TextField()),
                ("speaker", models.CharField(blank=True, max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("importance_score", models.FloatField(default=0.5)),
                ("is_ai_detected", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_moments",
                        to="voice_intelligence.voicerecording",
                    ),
                ),
            ],
            options={
                "db_table": "key_moments",
                "ordering": ["recording", "start_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ConversationSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "summary_type",
                    models.CharField(
                        choices=[
                            ("executive", "Executive Summary"),
                            ("detailed", "Detailed Summary"),
                            ("bullet_points", "Bullet Points"),
                            ("action_items", "Action Items Only"),
                        ],
                        default="executive",
                        max_length=20,
                    ),
                ),
                ("summary_text", models.TextField(blank=True)),
                ("key_points", models.JSONField(default=list)),
                ("topics", models.JSONField(default=list)),
                (
                    "topic_segments",
                    models.JSONField(default=list, help_text="Topics with time ranges"),
                ),
                ("decisions", models.JSONField(default=list)),
                ("questions_asked", models.JSONField(default=list)),
                ("questions_unanswered", models.JSONField(default=list)),
                ("next_steps", models.JSONField(default=list)),
                ("keywords", models.JSONField(default=list)),
                (
                    "entities_mentioned",
                    models.JSONField(
                        default=dict, help_text="People, companies, products mentioned"
                    ),
                ),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("generation_prompt", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="voice_intelligence.voicerecording",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_summaries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CallScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_score",
                    models.IntegerField(default=0, help_text="0-100 score"),
                ),
                ("opening_score", models.IntegerField(default=0)),
                ("discovery_score", models.IntegerField(default=0)),
                ("presentation_score", models.IntegerField(default=0)),
                ("objection_handling_score", models.IntegerField(default=0)),
                ("closing_score", models.IntegerField(default=0)),
                ("talk_to_listen_ratio", models.FloatField(blank=True, null=True)),
                (
                    "longest_monologue_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
                ("question_count", models.IntegerField(default=0)),
                ("words_per_minute", models.IntegerField(blank=True, null=True)),
                ("filler_word_count", models.IntegerField(default=0)),
                ("filler_words_used", models.JSONField(default=list)),
                ("customer_engagement_score", models.FloatField(blank=True, null=True)),
                ("interruption_count", models.IntegerField(default=0)),
                ("mentioned_value_prop", models.BooleanField(default=False)),
                ("asked_discovery_questions", models.BooleanField(default=False)),
                ("handled_objections", models.BooleanField(default=False)),
                ("established_next_steps", models.BooleanField(default=False)),
                ("personalized_conversation", models.BooleanField(default=False)),
                ("coaching_tips", models.JSONField(default=list)),
                ("areas_for_improvement", models.JSONField(default=list)),
                ("strengths", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recording",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_score",
                        to="voice_intelligence.voicerecording",
                    ),
                ),
            ],
            options={
                "db_table": "call_scores",
            },
        ),
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "assigned_to_name",
                    models.CharField(
                        blank=True, help_text="Name from transcript", max_length=200
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "mentioned_at_timestamp",
                    models.IntegerField(
                        blank=True, help_text="Seconds into recording", null=True
                    ),
                ),
                (
                    "context_quote",
                    models.TextField(
                        blank=True, help_text="Relevant quote from transcript"
                    ),
                ),
                ("speaker", models.CharField(blank=True, max_length=200)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0.8)),
                ("was_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_action_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_action_items",
                        to="task_management.task",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_items",
                        to="voice_intelligence.voicerecording",
                    ),
                ),
            ],
            options={
                "db_table": "action_items",
                "ordering": ["-priority", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="RecordingCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_auto_classified", models.BooleanField(default=False)),
                ("confidence", models.FloatField(default=1.0)),
                ("classified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="voice_intelligence.conversationcategory",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="voice_intelligence.voicerecording",
                    ),
                ),
            ],
            options={
                "db_table": "recording_categories",
                "unique_together": {("recording", "category")},
            },
        ),
    ]
