# Generated by Django 5.2.7 on 2026-01-24 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice_intelligence", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="voice_intelligence.conversationcategory",
            ),
            preserve_default=False,
        ),
    ]
