# Generated by Django 5.2.7 on 2025-11-23 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("multi_tenant", "0001_initial"),
        ("opportunity_management", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_sequential",
                    models.BooleanField(
                        default=True,
                        help_text="If True, steps execute in order. If False, all steps run in parallel.",
                    ),
                ),
                ("auto_start_on_create", models.BooleanField(default=False)),
                (
                    "trigger_conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Conditions to auto-start workflow: {"amount_gt": 10000, "status": "draft"}',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_instances", models.PositiveIntegerField(default=0)),
                ("completed_instances", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("approval", "Approval Required"),
                            ("review", "Review Only"),
                            ("notification", "Notification"),
                            ("condition", "Conditional Branch"),
                        ],
                        default="approval",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "approver_count_required",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of approvals required to pass this step",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Conditions to execute this step: {"field": "amount", "operator": "gt", "value": 5000}',
                    ),
                ),
                ("allow_delegate", models.BooleanField(default=True)),
                ("allow_comments", models.BooleanField(default=True)),
                (
                    "timeout_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Auto-escalate or auto-approve after this many hours",
                        null=True,
                    ),
                ),
                (
                    "timeout_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approve", "Auto-Approve"),
                            ("reject", "Auto-Reject"),
                            ("escalate", "Escalate"),
                        ],
                        default="escalate",
                        max_length=20,
                    ),
                ),
                (
                    "approvers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="approval_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="collaboration.approvalworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_instances",
                        to="collaboration.approvalstep",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="collaboration.approvalworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("public", "Public Channel"),
                            ("private", "Private Channel"),
                            ("direct", "Direct Message"),
                            ("group", "Group Chat"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("is_read_only", models.BooleanField(default=False)),
                ("allow_threads", models.BooleanField(default=True)),
                ("allow_file_sharing", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("member_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChannelMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_read_at", models.DateTimeField(auto_now_add=True)),
                ("is_muted", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("can_post", models.BooleanField(default=True)),
                ("can_invite", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collaboration.channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
            },
        ),
        migrations.AddField(
            model_name="channel",
            name="members",
            field=models.ManyToManyField(
                related_name="channels",
                through="collaboration.ChannelMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DealRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("private", "Private - Invite Only"),
                            ("team", "Team - All team members"),
                            ("public", "Public - Organization wide"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("document_count", models.PositiveIntegerField(default=0)),
                ("participant_count", models.PositiveIntegerField(default=0)),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deal_rooms",
                        to="opportunity_management.opportunity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_deal_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CollaborativeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("spreadsheet", "Spreadsheet"),
                            ("presentation", "Presentation"),
                            ("pdf", "PDF"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In Review"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("allow_comments", models.BooleanField(default=True)),
                ("allow_downloads", models.BooleanField(default=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="collaboration.collaborativedocument",
                    ),
                ),
                (
                    "deal_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="collaboration.dealroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DealRoomParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("contributor", "Contributor"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("can_invite", models.BooleanField(default=False)),
                ("can_edit_room", models.BooleanField(default=False)),
                ("can_upload_documents", models.BooleanField(default=True)),
                ("can_delete_messages", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("push_notifications", models.BooleanField(default=True)),
                (
                    "deal_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="collaboration.dealroom",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("position", models.JSONField(blank=True, null=True)),
                ("highlighted_text", models.TextField(blank=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="collaboration.collaborativedocument",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="collaboration.documentcomment",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("file", "File Attachment"),
                            ("system", "System Message"),
                            ("code", "Code Snippet"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("thread_reply_count", models.PositiveIntegerField(default=0)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("reactions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_edited", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="collaboration.channel",
                    ),
                ),
                (
                    "deal_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="collaboration.dealroom",
                    ),
                ),
                (
                    "mentioned_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mentioned_in_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="collaboration.message",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("delegated", "Delegated"),
                            ("commented", "Commented"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegated_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="collaboration.approvalinstance",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="collaboration.approvalstep",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["instance", "step"],
                        name="collaborati_instanc_41c896_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="collaborati_actor_i_7f3664_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="approvalworkflow",
            index=models.Index(
                fields=["organization", "is_active"],
                name="collaborati_organiz_a55fb2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalstep",
            index=models.Index(
                fields=["workflow", "order"], name="collaborati_workflo_e6e66c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalinstance",
            index=models.Index(
                fields=["organization", "status"], name="collaborati_organiz_123e96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalinstance",
            index=models.Index(
                fields=["requested_by", "status"], name="collaborati_request_2dcd52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalinstance",
            index=models.Index(
                fields=["workflow", "status"], name="collaborati_workflo_ad28b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalinstance",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="collaborati_content_bd0a81_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="channelmembership",
            unique_together={("channel", "user")},
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(
                fields=["organization", "channel_type"],
                name="collaborati_organiz_4aa818_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(
                fields=["created_by", "is_archived"],
                name="collaborati_created_ea5b58_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dealroom",
            index=models.Index(
                fields=["organization", "status"], name="collaborati_organiz_ba535b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealroom",
            index=models.Index(
                fields=["owner", "status"], name="collaborati_owner_i_834f33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborativedocument",
            index=models.Index(
                fields=["organization", "status"], name="collaborati_organiz_9211ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborativedocument",
            index=models.Index(
                fields=["owner", "status"], name="collaborati_owner_i_1c22c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborativedocument",
            index=models.Index(
                fields=["deal_room", "status"], name="collaborati_deal_ro_d2ebda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealroomparticipant",
            index=models.Index(
                fields=["deal_room", "is_active"], name="collaborati_deal_ro_eff3af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealroomparticipant",
            index=models.Index(
                fields=["user", "is_active"], name="collaborati_user_id_12b2fa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dealroomparticipant",
            unique_together={("deal_room", "user")},
        ),
        migrations.AddIndex(
            model_name="documentcomment",
            index=models.Index(
                fields=["document", "is_resolved"],
                name="collaborati_documen_963fd2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentcomment",
            index=models.Index(
                fields=["author", "created_at"], name="collaborati_author__b7a7ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["channel", "created_at"], name="collaborati_channel_4ec744_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["deal_room", "created_at"],
                name="collaborati_deal_ro_38d905_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["parent_message", "created_at"],
                name="collaborati_parent__918d08_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "created_at"], name="collaborati_sender__012734_idx"
            ),
        ),
    ]
