# Generated by Django 5.2.8 on 2025-11-12 04:14

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact_management", "0002_initial"),
        ("lead_management", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("mixed", "Mixed"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Email subject line", max_length=255),
                ),
                ("content_html", models.TextField(help_text="HTML email content")),
                (
                    "content_text",
                    models.TextField(blank=True, help_text="Plain text fallback"),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("enable_ab_test", models.BooleanField(default=False)),
                ("ab_test_variants", models.JSONField(blank=True, default=dict)),
                ("total_recipients", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("delivered_count", models.IntegerField(default=0)),
                ("opened_count", models.IntegerField(default=0)),
                ("clicked_count", models.IntegerField(default=0)),
                ("bounced_count", models.IntegerField(default=0)),
                ("unsubscribed_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "db_table": "crm_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        help_text="A/B test variant (A, B, etc.)",
                        max_length=50,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("first_clicked_at", models.DateTimeField(blank=True, null=True)),
                ("bounced_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("open_count", models.IntegerField(default=0)),
                ("click_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="campaign_management.campaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contact_management.contact",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead_management.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Recipient",
                "verbose_name_plural": "Campaign Recipients",
                "db_table": "crm_campaign_recipients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignClick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                ("clicked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="campaign_management.campaignrecipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Click",
                "verbose_name_plural": "Campaign Clicks",
                "db_table": "crm_campaign_clicks",
                "ordering": ["-clicked_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "filters",
                    models.JSONField(
                        default=dict,
                        help_text="Filter criteria: {lead_status: 'qualified', industry: 'tech', etc.}",
                    ),
                ),
                ("contact_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Segment",
                "verbose_name_plural": "Campaign Segments",
                "db_table": "crm_campaign_segments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaign_management.campaignsegment",
            ),
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome"),
                            ("nurture", "Nurture"),
                            ("promotion", "Promotion"),
                            ("newsletter", "Newsletter"),
                            ("transactional", "Transactional"),
                            ("followup", "Follow-up"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("content_html", models.TextField()),
                ("content_text", models.TextField(blank=True)),
                (
                    "variables",
                    models.JSONField(
                        default=list,
                        help_text="List of variables: ['first_name', 'company', 'custom_field']",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="email_templates/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_email_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
                "db_table": "crm_campaign_email_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="campaignrecipient",
            index=models.Index(
                fields=["campaign", "status"], name="crm_campaig_campaig_2ae5fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignrecipient",
            index=models.Index(fields=["email"], name="crm_campaig_email_4b04a5_idx"),
        ),
        migrations.AddIndex(
            model_name="campaignrecipient",
            index=models.Index(
                fields=["contact"], name="crm_campaig_contact_a81dd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignrecipient",
            index=models.Index(fields=["lead"], name="crm_campaig_lead_id_d905f1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="campaignrecipient",
            unique_together={("campaign", "email")},
        ),
        migrations.AddIndex(
            model_name="campaignclick",
            index=models.Index(
                fields=["recipient", "clicked_at"],
                name="crm_campaig_recipie_8ce34d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignclick",
            index=models.Index(fields=["url"], name="crm_campaig_url_261ac8_idx"),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["status", "scheduled_at"], name="crm_campaig_status_ad1252_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="crm_campaig_created_dbaaf0_idx",
            ),
        ),
    ]
