# Generated by Django 5.2.7 on 2025-11-23 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign_management", "0001_initial"),
        ("contact_management", "0002_initial"),
        ("lead_management", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("one_time", "One-Time"),
                            ("drip", "Drip Campaign"),
                            ("trigger", "Triggered"),
                            ("recurring", "Recurring"),
                        ],
                        default="one_time",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("from_email", models.EmailField(max_length=254)),
                ("from_name", models.CharField(blank=True, max_length=100)),
                ("reply_to", models.EmailField(blank=True, max_length=254, null=True)),
                ("html_content", models.TextField(help_text="HTML email content")),
                (
                    "text_content",
                    models.TextField(blank=True, help_text="Plain text fallback"),
                ),
                (
                    "target_segment",
                    models.JSONField(
                        default=dict, help_text="Audience segment criteria"
                    ),
                ),
                (
                    "exclude_segment",
                    models.JSONField(
                        blank=True, default=dict, help_text="Exclusion criteria"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "drip_sequence",
                    models.JSONField(
                        blank=True, default=list, help_text="List of drip emails"
                    ),
                ),
                ("track_opens", models.BooleanField(default=True)),
                ("track_clicks", models.BooleanField(default=True)),
                ("total_recipients", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("delivered_count", models.IntegerField(default=0)),
                ("opened_count", models.IntegerField(default=0)),
                ("clicked_count", models.IntegerField(default=0)),
                ("bounced_count", models.IntegerField(default=0)),
                ("unsubscribed_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaign_management.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Campaign",
                "verbose_name_plural": "Email Campaigns",
                "db_table": "campaign_email_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_url", models.URLField()),
                ("tracking_url", models.URLField(unique=True)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("click_count", models.IntegerField(default=0)),
                ("unique_click_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_links",
                        to="campaign_management.emailcampaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Link",
                "verbose_name_plural": "Email Links",
                "db_table": "campaign_email_clicks",
            },
        ),
        migrations.CreateModel(
            name="EmailRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("personalization_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("unsubscribed", "Unsubscribed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("first_opened_at", models.DateTimeField(blank=True, null=True)),
                ("last_opened_at", models.DateTimeField(blank=True, null=True)),
                ("first_clicked_at", models.DateTimeField(blank=True, null=True)),
                ("last_clicked_at", models.DateTimeField(blank=True, null=True)),
                ("open_count", models.IntegerField(default=0)),
                ("click_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "bounce_reason",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="campaign_management.emailcampaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contact_management.contact",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead_management.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Recipient",
                "verbose_name_plural": "Email Recipients",
                "db_table": "campaign_email_recipients",
            },
        ),
        migrations.CreateModel(
            name="EmailClick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="campaign_management.emaillink",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="campaign_management.emailrecipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Click",
                "verbose_name_plural": "Email Clicks",
                "db_table": "campaign_email_individual_clicks",
            },
        ),
        migrations.CreateModel(
            name="EmailUnsubscribe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("reason", models.TextField(blank=True)),
                ("unsubscribed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaign_management.emailcampaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contact_management.contact",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead_management.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Unsubscribe",
                "verbose_name_plural": "Email Unsubscribes",
                "db_table": "campaign_email_unsubscribes",
            },
        ),
        migrations.AddIndex(
            model_name="emailrecipient",
            index=models.Index(
                fields=["campaign", "status"], name="campaign_em_campaig_8b8833_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailrecipient",
            index=models.Index(fields=["email"], name="campaign_em_email_17354d_idx"),
        ),
        migrations.AddIndex(
            model_name="emailclick",
            index=models.Index(
                fields=["recipient", "clicked_at"],
                name="campaign_em_recipie_0f1623_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailclick",
            index=models.Index(
                fields=["link", "clicked_at"], name="campaign_em_link_id_9d4cb7_idx"
            ),
        ),
    ]
