# Generated by Django 5.2.7 on 2026-01-24 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaign_management",
            "0002_emailcampaign_emaillink_emailrecipient_emailclick_and_more",
        ),
        (
            "contact_management",
            "0003_alter_contact_assigned_to_alter_contact_created_by",
        ),
        ("lead_management", "0003_alter_lead_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignclick",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailcampaign",
            name="template",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaign_management.emailtemplate",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailrecipient",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contact_management.contact",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailrecipient",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lead_management.lead",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailunsubscribe",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaign_management.emailcampaign",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailunsubscribe",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contact_management.contact",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailunsubscribe",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lead_management.lead",
            ),
            preserve_default=False,
        ),
    ]
