# Generated by Django 6.0 on 2026-01-29 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign_management", "0003_alter_campaignclick_ip_address_and_more"),
        (
            "contact_management",
            "0003_alter_contact_assigned_to_alter_contact_created_by",
        ),
        ("lead_management", "0003_alter_lead_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaign_management.emailtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="emailclick",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailrecipient",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contact_management.contact",
            ),
        ),
        migrations.AlterField(
            model_name="emailrecipient",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lead_management.lead",
            ),
        ),
        migrations.AlterField(
            model_name="emailunsubscribe",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaign_management.emailcampaign",
            ),
        ),
        migrations.AlterField(
            model_name="emailunsubscribe",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contact_management.contact",
            ),
        ),
        migrations.AlterField(
            model_name="emailunsubscribe",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lead_management.lead",
            ),
        ),
    ]
