# Generated by Django 5.2.7 on 2026-01-24 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_workflow", models.CharField(max_length=255)),
                ("modifications", models.JSONField(default=dict)),
                (
                    "generation_method",
                    models.CharField(default="generative_ai", max_length=100),
                ),
                ("status", models.CharField(default="testing", max_length=20)),
                ("created_by_ai", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIWorkflowProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("workflow_name", models.CharField(max_length=255)),
                ("proposal_description", models.TextField()),
                ("expected_improvement", models.FloatField()),
                ("confidence_score", models.FloatField()),
                ("reasoning", models.TextField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ABTestResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("control_value", models.FloatField()),
                ("variant_value", models.FloatField()),
                ("improvement_percentage", models.FloatField()),
                ("statistical_significance", models.FloatField()),
                ("sample_size", models.IntegerField()),
                ("test_date", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="autonomous_workflow.workflowvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-test_date"],
            },
        ),
    ]
