import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact_management', '0003_alter_contact_assigned_to_alter_contact_created_by'),
        ('opportunity_management', '0003_alter_opportunity_assigned_to'),
        ('user_management', '0005_alter_user_last_login_alter_user_last_login_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEmailDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('cold_outreach', 'Cold Outreach'), ('follow_up', 'Follow Up'), ('proposal', 'Proposal'), ('meeting_request', 'Meeting Request'), ('thank_you', 'Thank You'), ('re_engagement', 'Re-engagement'), ('objection_handling', 'Objection Handling'), ('closing', 'Closing'), ('custom', 'Custom')], max_length=50)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('casual', 'Casual'), ('formal', 'Formal'), ('urgent', 'Urgent')], default='professional', max_length=20)),
                ('context', models.TextField(help_text='Additional context for AI')),
                ('key_points', models.JSONField(default=list, help_text='Key points to include')),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('variations', models.JSONField(default=list, help_text='Alternative versions')),
                ('was_used', models.BooleanField(default=False)),
                ('user_rating', models.IntegerField(blank=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to='contact_management.contact')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to='opportunity_management.opportunity')),
                ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='ai_email_drafts', to='user_management.user')),
            ],
            options={
                'db_table': 'ai_email_drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesCoachAdvice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advice_type', models.CharField(choices=[('deal_strategy', 'Deal Strategy'), ('objection_response', 'Objection Response'), ('negotiation_tip', 'Negotiation Tip'), ('timing_suggestion', 'Timing Suggestion'), ('relationship_building', 'Relationship Building'), ('competitive_positioning', 'Competitive Positioning'), ('upsell_opportunity', 'Upsell Opportunity'), ('risk_mitigation', 'Risk Mitigation')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('advice', models.TextField()),
                ('reasoning', models.TextField(help_text='Why this advice is given')),
                ('action_items', models.JSONField(default=list)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('was_helpful', models.BooleanField(null=True)),
                ('outcome', models.TextField(blank=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True)),
                ('contact', models.ForeignKey(blank=True, on_delete=models.CASCADE, to='contact_management.contact')),
                ('opportunity', models.ForeignKey(blank=True, on_delete=models.CASCADE, related_name='ai_advice', to='opportunity_management.opportunity')),
                ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='sales_coaching', to='user_management.user')),
            ],
            options={
                'db_table': 'sales_coach_advice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('price', 'Price/Budget'), ('timing', 'Timing'), ('competitor', 'Competitor'), ('authority', 'Decision Authority'), ('need', 'Need/Fit'), ('trust', 'Trust/Risk'), ('implementation', 'Implementation'), ('other', 'Other')], max_length=50)),
                ('objection', models.TextField(help_text="The customer's objection")),
                ('keywords', models.JSONField(default=list, help_text='Keywords to match')),
                ('responses', models.JSONField(default=list, help_text='List of response options')),
                ('best_response', models.TextField(help_text='The recommended response')),
                ('when_to_use', models.TextField(blank=True)),
                ('follow_up_questions', models.JSONField(default=list)),
                ('times_used', models.IntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to='user_management.user')),
            ],
            options={
                'db_table': 'objection_responses',
                'ordering': ['-times_used', 'category'],
            },
        ),
        migrations.CreateModel(
            name='CallScript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('script_type', models.CharField(choices=[('discovery', 'Discovery Call'), ('demo', 'Demo Call'), ('follow_up', 'Follow-up Call'), ('closing', 'Closing Call'), ('cold_call', 'Cold Call'), ('check_in', 'Check-in Call')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('opening', models.TextField(help_text='Opening statement')),
                ('discovery_questions', models.JSONField(default=list)),
                ('value_propositions', models.JSONField(default=list)),
                ('objection_handlers', models.JSONField(default=dict)),
                ('closing_techniques', models.JSONField(default=list)),
                ('next_steps', models.TextField(blank=True)),
                ('personalized_points', models.JSONField(default=list)),
                ('times_used', models.IntegerField(default=0)),
                ('avg_call_duration', models.IntegerField(null=True)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_template', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='call_scripts', to='user_management.user')),
            ],
            options={
                'db_table': 'call_scripts',
                'ordering': ['-times_used', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DealInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('win_factor', 'Win Factor'), ('risk_factor', 'Risk Factor'), ('opportunity', 'Opportunity'), ('warning', 'Warning'), ('suggestion', 'Suggestion'), ('benchmark', 'Benchmark Comparison')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('insight', models.TextField()),
                ('data_points', models.JSONField(default=list)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('impact_score', models.IntegerField(default=0)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('is_actioned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True)),
                ('opportunity', models.ForeignKey(on_delete=models.CASCADE, related_name='ai_insights', to='opportunity_management.opportunity')),
            ],
            options={
                'db_table': 'deal_insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WinLossAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(max_length=20)),
                ('primary_factors', models.JSONField(default=list, help_text='Main reasons for outcome')),
                ('secondary_factors', models.JSONField(default=list)),
                ('what_worked', models.JSONField(default=list)),
                ('what_didnt_work', models.JSONField(default=list)),
                ('competitor_impact', models.TextField(blank=True)),
                ('lessons_learned', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('deal_duration_days', models.IntegerField(null=True)),
                ('stakeholders_involved', models.IntegerField(null=True)),
                ('touchpoints_count', models.IntegerField(null=True)),
                ('similar_won_deals', models.JSONField(default=list)),
                ('similar_lost_deals', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.OneToOneField(on_delete=models.CASCADE, related_name='win_loss_analysis', to='opportunity_management.opportunity')),
            ],
            options={
                'db_table': 'win_loss_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonaProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('typical_titles', models.JSONField(default=list)),
                ('typical_industries', models.JSONField(default=list)),
                ('company_size_range', models.CharField(blank=True, max_length=100)),
                ('motivations', models.JSONField(default=list)),
                ('pain_points', models.JSONField(default=list)),
                ('goals', models.JSONField(default=list)),
                ('fears', models.JSONField(default=list)),
                ('preferred_channels', models.JSONField(default=list)),
                ('communication_style', models.TextField(blank=True)),
                ('best_times_to_contact', models.JSONField(default=list)),
                ('key_value_props', models.JSONField(default=list)),
                ('common_objections', models.JSONField(default=list)),
                ('winning_approaches', models.JSONField(default=list)),
                ('things_to_avoid', models.JSONField(default=list)),
                ('content_types_preferred', models.JSONField(default=list)),
                ('contacts_matched', models.IntegerField(default=0)),
                ('deals_won', models.IntegerField(default=0)),
                ('deals_lost', models.IntegerField(default=0)),
                ('avg_deal_size', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET_NULL, to='user_management.user')),
            ],
            options={
                'db_table': 'persona_profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactPersonaMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matching_factors', models.JSONField(default=list)),
                ('recommended_approach', models.TextField(blank=True)),
                ('talking_points', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=models.CASCADE, related_name='persona_matches', to='contact_management.contact')),
                ('persona', models.ForeignKey(on_delete=models.CASCADE, to='ai_sales_assistant.personaprofile')),
            ],
            options={
                'db_table': 'contact_persona_matches',
                'ordering': ['-confidence_score'],
                'unique_together': {('contact', 'persona')},
            },
        ),
    ]
