# Generated by Django 5.2.7 on 2026-01-24 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("data_access", "Data Access Agreement"),
                            ("service_level", "Service Level Agreement"),
                            ("payment", "Payment Contract"),
                            ("loyalty", "Loyalty Program"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "party_a",
                    models.CharField(
                        help_text="Wallet address of party A", max_length=255
                    ),
                ),
                (
                    "party_b",
                    models.CharField(
                        help_text="Wallet address of party B", max_length=255
                    ),
                ),
                ("terms", models.JSONField(default=dict)),
                (
                    "conditions",
                    models.JSONField(default=list, help_text="Execution conditions"),
                ),
                ("contract_address", models.CharField(max_length=255)),
                ("deployment_tx", models.CharField(max_length=255)),
                (
                    "blockchain_network",
                    models.CharField(default="ethereum", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("executed", "Executed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("deployed_at", models.DateTimeField()),
                ("executed_at", models.DateTimeField(blank=True)),
            ],
            options={
                "ordering": ["-deployed_at"],
            },
        ),
        migrations.CreateModel(
            name="DataWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wallet_address", models.CharField(max_length=255, unique=True)),
                ("public_key", models.TextField()),
                (
                    "blockchain_network",
                    models.CharField(
                        choices=[
                            ("ethereum", "Ethereum"),
                            ("polygon", "Polygon"),
                            ("solana", "Solana"),
                        ],
                        default="ethereum",
                        max_length=50,
                    ),
                ),
                (
                    "data_schema",
                    models.JSONField(
                        default=dict, help_text="Schema of user-controlled data"
                    ),
                ),
                (
                    "active_permissions",
                    models.JSONField(
                        default=list, help_text="Active access permissions granted"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("last_sync", models.DateTimeField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Wallet",
                "verbose_name_plural": "Data Wallets",
            },
        ),
        migrations.CreateModel(
            name="DataAccessGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requester",
                    models.CharField(
                        help_text="Organization requesting access", max_length=255
                    ),
                ),
                (
                    "data_categories",
                    models.JSONField(
                        default=list, help_text="Categories of data granted"
                    ),
                ),
                ("purpose", models.TextField()),
                ("contract_address", models.CharField(max_length=255)),
                ("transaction_hash", models.CharField(max_length=255)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("access_count", models.IntegerField(default=0)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grants",
                        to="web3_integration.datawallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-granted_at"],
            },
        ),
        migrations.CreateModel(
            name="NFTLoyaltyReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_id", models.CharField(max_length=255, unique=True)),
                ("contract_address", models.CharField(max_length=255)),
                ("metadata_uri", models.URLField()),
                ("reward_type", models.CharField(max_length=100)),
                ("reward_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("points_value", models.IntegerField(default=0)),
                ("milestone", models.CharField(max_length=255)),
                ("milestone_date", models.DateTimeField()),
                ("is_redeemed", models.BooleanField(default=False)),
                ("redeemed_at", models.DateTimeField(blank=True)),
                (
                    "redemption_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15),
                ),
                ("minted_at", models.DateTimeField()),
                ("transaction_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nft_rewards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NFT Loyalty Reward",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockchainTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transaction_hash", models.CharField(max_length=255, unique=True)),
                ("blockchain_network", models.CharField(max_length=50)),
                ("block_number", models.BigIntegerField(blank=True)),
                ("transaction_type", models.CharField(max_length=100)),
                ("from_address", models.CharField(max_length=255)),
                ("to_address", models.CharField(max_length=255)),
                ("value", models.CharField(blank=True, max_length=100)),
                ("gas_used", models.BigIntegerField(blank=True)),
                ("gas_price", models.BigIntegerField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blockchain_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_hash"],
                        name="web3_integr_transac_da122f_idx",
                    )
                ],
            },
        ),
    ]
