# Generated by Django 5.2.7 on 2025-11-23 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("multi_tenant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("essential", "Essential"),
                            ("functional", "Functional"),
                            ("analytics", "Analytics"),
                            ("marketing", "Marketing"),
                            ("third_party", "Third Party"),
                        ],
                        default="functional",
                        max_length=50,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("version", models.IntegerField(default=1)),
                (
                    "legal_basis",
                    models.CharField(
                        choices=[
                            ("consent", "Consent"),
                            ("contract", "Contract"),
                            ("legal_obligation", "Legal Obligation"),
                            ("vital_interests", "Vital Interests"),
                            ("public_task", "Public Task"),
                            ("legitimate_interests", "Legitimate Interests"),
                        ],
                        default="consent",
                        max_length=100,
                    ),
                ),
                (
                    "retention_period_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of days to retain data. Null means indefinite.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
            ],
            options={
                "db_table": "gdpr_consent_types",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="DataBreachIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "breach_type",
                    models.CharField(
                        choices=[
                            ("confidentiality", "Confidentiality Breach"),
                            ("integrity", "Integrity Breach"),
                            ("availability", "Availability Breach"),
                            ("combined", "Combined Breach"),
                        ],
                        max_length=100,
                    ),
                ),
                ("discovered_at", models.DateTimeField()),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("affected_users_count", models.IntegerField(default=0)),
                ("data_categories_affected", models.JSONField(default=list)),
                ("breach_cause", models.TextField()),
                ("containment_measures", models.TextField(blank=True)),
                ("remediation_plan", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Identified"),
                            ("investigating", "Investigating"),
                            ("contained", "Contained"),
                            ("remediated", "Remediated"),
                            ("closed", "Closed"),
                        ],
                        default="identified",
                        max_length=50,
                    ),
                ),
                ("authority_notified", models.BooleanField(default=False)),
                (
                    "authority_notification_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("users_notified", models.BooleanField(default=False)),
                ("user_notification_date", models.DateTimeField(blank=True, null=True)),
                (
                    "notification_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether notification to authorities is required (within 72 hours)",
                    ),
                ),
                ("risk_assessment", models.TextField(blank=True)),
                ("lessons_learned", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "affected_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="data_breaches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_breaches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gdpr_breach_incidents",
                "ordering": ["-discovered_at"],
            },
        ),
        migrations.CreateModel(
            name="DataDeletionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "deletion_type",
                    models.CharField(
                        choices=[
                            ("full_deletion", "Full Account Deletion"),
                            ("anonymization", "Data Anonymization"),
                            ("specific_data", "Specific Data Deletion"),
                        ],
                        default="full_deletion",
                        max_length=50,
                    ),
                ),
                (
                    "data_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Specific data categories to delete",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("backup_created", models.BooleanField(default=False)),
                ("backup_location", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gdpr_data_deletion_requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="DataExportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("full_export", "Full Data Export"),
                            ("specific_data", "Specific Data Categories"),
                            ("portability", "Data Portability"),
                        ],
                        default="full_export",
                        max_length=50,
                    ),
                ),
                (
                    "data_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of specific data categories to export",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("csv", "CSV"),
                            ("xml", "XML"),
                            ("pdf", "PDF"),
                        ],
                        default="json",
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(blank=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_export_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gdpr_data_export_requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="DataProcessingActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("purpose", models.TextField(help_text="Purpose of processing")),
                (
                    "legal_basis",
                    models.CharField(
                        choices=[
                            ("consent", "Consent"),
                            ("contract", "Contract"),
                            ("legal_obligation", "Legal Obligation"),
                            ("vital_interests", "Vital Interests"),
                            ("public_task", "Public Task"),
                            ("legitimate_interests", "Legitimate Interests"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "data_categories",
                    models.JSONField(
                        default=list, help_text="Categories of personal data processed"
                    ),
                ),
                (
                    "data_subjects",
                    models.JSONField(
                        default=list,
                        help_text="Categories of data subjects (customers, employees, etc.)",
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        default=list,
                        help_text="Categories of recipients of personal data",
                    ),
                ),
                ("third_country_transfers", models.BooleanField(default=False)),
                ("third_countries", models.JSONField(blank=True, default=list)),
                (
                    "safeguards",
                    models.TextField(
                        blank=True, help_text="Safeguards for international transfers"
                    ),
                ),
                ("retention_period", models.CharField(max_length=200)),
                (
                    "security_measures",
                    models.TextField(
                        help_text="Technical and organizational security measures"
                    ),
                ),
                ("data_controller", models.CharField(max_length=200)),
                ("data_processor", models.CharField(blank=True, max_length=200)),
                (
                    "dpo_contact",
                    models.EmailField(
                        blank=True,
                        help_text="Data Protection Officer contact",
                        max_length=254,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_reviewed", models.DateField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
            ],
            options={
                "db_table": "gdpr_processing_activities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("version", models.CharField(max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("effective_date", models.DateField()),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("privacy_policy", "Privacy Policy"),
                            ("cookie_policy", "Cookie Policy"),
                            ("data_processing", "Data Processing Agreement"),
                            ("terms_of_service", "Terms of Service"),
                        ],
                        default="privacy_policy",
                        max_length=50,
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("requires_acceptance", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
            ],
            options={
                "db_table": "gdpr_privacy_notices",
                "ordering": ["-effective_date", "-version"],
            },
        ),
        migrations.CreateModel(
            name="UserPrivacyPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_data_processing", models.BooleanField(default=True)),
                ("allow_marketing_emails", models.BooleanField(default=False)),
                ("allow_analytics", models.BooleanField(default=True)),
                ("allow_third_party_sharing", models.BooleanField(default=False)),
                ("allow_profiling", models.BooleanField(default=False)),
                (
                    "data_retention_preference",
                    models.CharField(
                        choices=[
                            ("minimum", "Minimum Required"),
                            ("standard", "Standard Period"),
                            ("extended", "Extended Period"),
                        ],
                        default="standard",
                        max_length=50,
                    ),
                ),
                (
                    "contact_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Preferred contact methods and frequencies",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_privacy_notices",
                    models.ManyToManyField(
                        blank=True, to="gdpr_compliance.privacynotice"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gdpr_user_privacy_preferences",
            },
        ),
        migrations.CreateModel(
            name="DataAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("export", "Export"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "data_fields",
                    models.JSONField(
                        blank=True, default=list, help_text="Specific fields accessed"
                    ),
                ),
                ("purpose", models.CharField(blank=True, max_length=200)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "accessed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_accesses_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gdpr_data_access_logs",
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "accessed_at"],
                        name="gdpr_data_a_user_id_40fafc_idx",
                    ),
                    models.Index(
                        fields=["accessed_by", "accessed_at"],
                        name="gdpr_data_a_accesse_999198_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="gdpr_data_a_content_982d75_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_granted", models.BooleanField(default=False)),
                ("consent_date", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "consent_method",
                    models.CharField(
                        choices=[
                            ("explicit", "Explicit Opt-in"),
                            ("implicit", "Implicit"),
                            ("pre_checked", "Pre-checked Box"),
                            ("opt_out", "Opt-out"),
                        ],
                        default="explicit",
                        max_length=50,
                    ),
                ),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                ("version", models.IntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "consent_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_consents",
                        to="gdpr_compliance.consenttype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="multi_tenant.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gdpr_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gdpr_user_consents",
                "ordering": ["-consent_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "consent_type"],
                        name="gdpr_user_c_user_id_95050d_idx",
                    ),
                    models.Index(
                        fields=["is_granted", "withdrawn_at"],
                        name="gdpr_user_c_is_gran_b3d89e_idx",
                    ),
                ],
            },
        ),
    ]
