# Generated by Django 5.2.7 on 2026-01-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdpr_compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataaccesslog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
