# Generated by Django 5.2.7 on 2026-01-24 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarMeeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=60)),
                ("platform", models.CharField(max_length=100)),
                ("meeting_url", models.URLField()),
                ("spatial_audio_enabled", models.BooleanField(default=True)),
                ("haptic_feedback_enabled", models.BooleanField(default=False)),
                ("real_time_translation", models.BooleanField(default=True)),
                ("recording_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="avatar_meetings", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="VirtualShowroom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("decentraland", "Decentraland"),
                            ("sandbox", "The Sandbox"),
                            ("horizon", "Horizon Worlds"),
                            ("spatial", "Spatial"),
                        ],
                        max_length=100,
                    ),
                ),
                ("url", models.URLField()),
                ("products", models.JSONField(default=list)),
                ("visitors_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetaverseProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("model_3d_url", models.URLField()),
                ("interactions_count", models.IntegerField(default=0)),
                ("demo_requests", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products_detailed",
                        to="metaverse_experiences.virtualshowroom",
                    ),
                ),
            ],
        ),
    ]
