# Generated by Django 5.2.7 on 2026-01-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0004_alter_auditlog_user_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
