# Generated by Django 5.2.7 on 2026-01-24 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HolographicAvatar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("model_url", models.URLField()),
                ("appearance_settings", models.JSONField(default=dict)),
                ("gesture_library", models.JSONField(default=list)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holographic_avatar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HolographicSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=60)),
                ("hologram_quality", models.CharField(default="high", max_length=20)),
                ("gesture_controls_enabled", models.BooleanField(default=True)),
                ("bandwidth_requirement_mbps", models.IntegerField(default=50)),
                ("recording_url", models.URLField(blank=True)),
                ("status", models.CharField(default="scheduled", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_holo_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="holo_sessions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
            },
        ),
    ]
