"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import socket
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Validate SECRET_KEY
if not SECRET_KEY:
    if DEBUG:
        # In development, generate a temporary key
        import secrets
        SECRET_KEY = secrets.token_urlsafe(50)
        print("WARNING: Using temporary SECRET_KEY in development. Set SECRET_KEY environment variable for production.")
    else:
        raise ValueError("SECRET_KEY environment variable is required in production")

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'daphne',  # WebSocket support - must be first
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',  # WebSocket channels
    'django_celery_beat',
    'django_filters',
    'drf_spectacular',
    # Enterprise Core Module
    'core',
    # Unified API
    'api',
    # CRM Modules
    'user_management',
    'contact_management',
    'lead_management',
    'opportunity_management',
    'task_management',
    'communication_management',
    'campaign_management',
    'document_management',
    'integration_hub',
    'activity_feed',
    'lead_qualification',
    'advanced_reporting',
    'reporting',
    # New Advanced Features
    'ai_insights',
    'gamification',
    'multi_tenant',
    'sso_integration',
    'collaboration',
    'gdpr_compliance',
    # Premium Revenue Features
    'revenue_intelligence',
    'email_tracking',
    'smart_scheduling',
    'ai_sales_assistant',
    'social_selling',
    'document_esign',
    'conversation_intelligence',
    'white_label',
    'customer_success',
    # AI Workflow Automation Features
    'email_sequence_automation',
    'predictive_lead_routing',
    'data_enrichment',
    'voice_intelligence',
    # Enterprise Features (New)
    'ai_chatbot',
    'app_marketplace',
    'esg_reporting',
    'realtime_collaboration',
    'enterprise',
    'customer_portal',
    'social_inbox',
    # Futuristic Next-Gen Features
    'quantum_modeling',
    'web3_integration',
    'metaverse_experiences',
    'ethical_ai_oversight',
    'carbon_tracking',
    'neurological_feedback',
    'holographic_collab',
    'autonomous_workflow',
    'interplanetary_sync',
    'biofeedback_personalization',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.SecurityHeadersMiddleware',  # Security headers
    'core.middleware.RequestLoggingMiddleware',  # Request logging
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'multi_tenant.middleware.TenantMiddleware',  # Multi-tenant middleware (after auth)
    'core.security.SecurityMiddleware',  # Enterprise security middleware (after auth)
    'core.middleware.RateLimitMiddleware',  # Global rate limiting
    'core.middleware.IPWhitelistMiddleware',  # Admin IP whitelist
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'

# Small helper: resolve env host names and fall back to a local address when unresolved
def _resolve_env_host(env_name: str, default: str = 'localhost') -> str:
    """Return a usable host string for the given environment variable.

    Tries to resolve the configured hostname with socket.getaddrinfo().
    If resolution fails, a safe fallback of 127.0.0.1 is returned and a
    warning is emitted so developers understand why 'db' -> getaddrinfo
    can fail when running Django outside of Docker.
    """
    host = os.getenv(env_name, default)
    try:
        # Try a quick name resolution; port is None (no port check)
        socket.getaddrinfo(host, None)
        return host
    except Exception:
        # Non-resolvable host (e.g. "db" on a non-Docker host)
        fallback = '127.0.0.1'
        if host != fallback:
            import warnings
            warnings.warn(
                f"Configured host {host!r} could not be resolved (getaddrinfo failed). "
                f"Falling back to {fallback!r}. If you intended to connect to a Docker "
                "service, either run the app inside the same compose network or set the "
                "DATABASE_HOST appropriately.", stacklevel=2
            )
        return fallback

# Channels Configuration
REDIS_HOST = _resolve_env_host('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.getenv('REDIS_PORT', '6379'))
REDIS_DB = int(os.getenv('REDIS_DB', '0'))

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(REDIS_HOST, REDIS_PORT)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Check if USE_SQLITE is set in environment
USE_SQLITE = os.getenv('USE_SQLITE', 'False') == 'True'

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DATABASE_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('DATABASE_NAME', 'mycrm_db'),
            'USER': os.getenv('DATABASE_USER', 'mycrm_user'),
            'PASSWORD': os.getenv('DATABASE_PASSWORD', ''),
            # resolve host names so running Django locally with DATABASE_HOST=db
            # doesn't immediately blow up with getaddrinfo errors
            'HOST': _resolve_env_host('DATABASE_HOST', 'localhost'),
            'PORT': os.getenv('DATABASE_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'TRAILING_SLASH': False,
}

# API Documentation with drf-spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'MyCRM API',
    'DESCRIPTION': 'Comprehensive CRM API for managing leads, contacts, opportunities, tasks, and more',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/',
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'AUTHENTICATION_WHITELIST': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# JWT Configuration
JWT_SIGNING_KEY = os.getenv('JWT_SIGNING_KEY', SECRET_KEY)
SIMPLE_JWT = {
    # Conservative defaults — shorter access token lifetime and reasonable refresh token lifetime
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', '15'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', '10080'))),  # 7 days by default
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'SIGNING_KEY': JWT_SIGNING_KEY,
}

# CORS Configuration
# Allow origins from env var or fall back to FRONTEND_URL and common localhost origins
_cors_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
if _cors_env:
    CORS_ALLOWED_ORIGINS = _cors_env.split(',')
else:
    CORS_ALLOWED_ORIGINS = list(filter(None, [
        os.getenv('FRONTEND_URL', 'http://localhost:3000'),
        'http://127.0.0.1:3000',
    ]))

CORS_ALLOW_CREDENTIALS = True

# Ensure common headers and methods are allowed (including Authorization)
try:
    from corsheaders.defaults import default_headers, default_methods  # type: ignore
    CORS_ALLOW_HEADERS = list(default_headers) + ['content-type', 'authorization']
    CORS_ALLOW_METHODS = list(default_methods)
except Exception:
    # Fallback to reasonable defaults if corsheaders package doesn't expose defaults
    CORS_ALLOW_HEADERS = ['accept', 'accept-encoding', 'authorization', 'content-type',
                          'dnt', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with']
    CORS_ALLOW_METHODS = ['DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT']

# Allow localhost regex for convenience in development
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://localhost(:\d+)?$",
    r"^https?://127\.0\.0\.1(:\d+)?$",
]

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'
# Make cookies HttpOnly by default (safe for production) and provide a SameSite option
SESSION_COOKIE_HTTPONLY = os.getenv('SESSION_COOKIE_HTTPONLY', 'True') == 'True'
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))

if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Enforce stricter cookie handling in production
    SESSION_COOKIE_HTTPONLY = True
    # Ensure SameSite is set to a conservative default in production
    SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')

# Enterprise Security Configuration
ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY', '')  # Generate with Fernet.generate_key()
if not ENCRYPTION_KEY:
    import warnings
    warnings.warn('ENCRYPTION_KEY not set! Enterprise encryption features will not work.', stacklevel=2)

# Rate Limiting Configuration
RATE_LIMIT_ENABLED = True
DEFAULT_RATE_LIMIT = int(os.getenv('DEFAULT_RATE_LIMIT', '100'))  # requests per hour
ADMIN_RATE_LIMIT = int(os.getenv('ADMIN_RATE_LIMIT', '1000'))  # requests per hour for admins

# Audit Logging Configuration
AUDIT_LOG_ENABLED = os.getenv('AUDIT_LOG_ENABLED', 'True') == 'True'
AUDIT_SENSITIVE_FIELDS = ['password', 'ssn', 'credit_card']

# Data Retention Policies
AUDIT_LOG_RETENTION_DAYS = int(os.getenv('AUDIT_LOG_RETENTION_DAYS', '365'))
BACKUP_RETENTION_DAYS = int(os.getenv('BACKUP_RETENTION_DAYS', '90'))
SESSION_TIMEOUT_MINUTES = int(os.getenv('SESSION_TIMEOUT_MINUTES', '120'))

# Enterprise Features
ENABLE_WORKFLOWS = os.getenv('ENABLE_WORKFLOWS', 'True') == 'True'
ENABLE_INTEGRATIONS = os.getenv('ENABLE_INTEGRATIONS', 'True') == 'True'
ENABLE_ADVANCED_ANALYTICS = os.getenv('ENABLE_ADVANCED_ANALYTICS', 'True') == 'True'
ENABLE_COMPLIANCE_REPORTING = os.getenv('ENABLE_COMPLIANCE_REPORTING', 'True') == 'True'

# Email Configuration (for notifications)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@mycrm.com')

# SendGrid Configuration (alternative)
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY', '')

# Twilio Configuration
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')

# Celery Configuration (for background tasks)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# SSO Configuration
BASE_URL = os.getenv('BASE_URL', 'http://localhost:8000')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')
SSO_SESSION_TIMEOUT = int(os.getenv('SSO_SESSION_TIMEOUT', '3600'))  # 1 hour

# OAuth Configuration
OAUTH_CLIENT_ID = os.getenv('OAUTH_CLIENT_ID', '')
OAUTH_CLIENT_SECRET = os.getenv('OAUTH_CLIENT_SECRET', '')
OAUTH_REDIRECT_URI = os.getenv('OAUTH_REDIRECT_URI', '')

# Sentry Error Tracking
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        traces_sample_rate=0.1,
        profiles_sample_rate=0.1,
        environment='production' if not DEBUG else 'development',
        send_default_pii=False,  # Don't send PII data
    )

# =====================
# SECURITY SETTINGS
# =====================

# Admin IP Whitelist (empty means no restriction in development)
ADMIN_IP_WHITELIST = os.getenv('ADMIN_IP_WHITELIST', '').split(',') if os.getenv('ADMIN_IP_WHITELIST') else []

# Security Headers
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'

    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'

# Password Requirements
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # Stronger password requirement
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Django Axes - Brute Force Protection
AXES_ENABLED = not DEBUG
AXES_FAILURE_LIMIT = 5  # Lock after 5 failed attempts
AXES_COOLOFF_TIME = timedelta(minutes=30)
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
AXES_RESET_ON_SUCCESS = True

# =====================
# MONITORING & APM
# =====================

VERSION = os.getenv('APP_VERSION', '1.0.0')

# Prometheus Metrics
PROMETHEUS_ENABLED = os.getenv('PROMETHEUS_ENABLED', 'true').lower() == 'true'

# Datadog APM
DATADOG_ENABLED = os.getenv('DATADOG_ENABLED', 'false').lower() == 'true'
if DATADOG_ENABLED and not DEBUG:
    DATADOG_API_KEY = os.getenv('DATADOG_API_KEY', '')
    DATADOG_APP_KEY = os.getenv('DATADOG_APP_KEY', '')
    DATADOG_STATSD_HOST = os.getenv('DATADOG_STATSD_HOST', 'localhost')
    DATADOG_STATSD_PORT = int(os.getenv('DATADOG_STATSD_PORT', '8125'))

# OpenTelemetry
OTEL_ENABLED = os.getenv('OTEL_ENABLED', 'false').lower() == 'true'
if OTEL_ENABLED:
    OTEL_SERVICE_NAME = os.getenv('OTEL_SERVICE_NAME', 'mycrm-backend')
    OTEL_EXPORTER_OTLP_ENDPOINT = os.getenv('OTEL_EXPORTER_OTLP_ENDPOINT', 'http://localhost:4317')

# =====================
# LOGGING CONFIGURATION
# =====================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'mycrm.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'security': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security'],
            'level': 'WARNING',
            'propagate': False,
        },
        'core.middleware': {
            'handlers': ['security'],
            'level': 'WARNING',
            'propagate': False,
        },
        'axes': {
            'handlers': ['security'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)
