# Generated by Django 5.2.8 on 2025-11-12 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales Dashboard"),
                            ("marketing", "Marketing Dashboard"),
                            ("executive", "Executive Dashboard"),
                            ("team", "Team Dashboard"),
                            ("custom", "Custom Dashboard"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "layout",
                    models.JSONField(
                        default=dict, help_text="Dashboard layout configuration"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Visible to all users"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "crm_dashboard",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("metric", "Metric Card"),
                            ("chart_line", "Line Chart"),
                            ("chart_bar", "Bar Chart"),
                            ("chart_pie", "Pie Chart"),
                            ("chart_area", "Area Chart"),
                            ("table", "Data Table"),
                            ("funnel", "Funnel Chart"),
                            ("heatmap", "Heat Map"),
                            ("list", "List View"),
                            ("progress", "Progress Bar"),
                            ("gauge", "Gauge"),
                            ("map", "Geographic Map"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("leads", "Leads"),
                            ("contacts", "Contacts"),
                            ("opportunities", "Opportunities"),
                            ("tasks", "Tasks"),
                            ("campaigns", "Campaigns"),
                            ("activities", "Activities"),
                            ("custom_query", "Custom Query"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "query_config",
                    models.JSONField(
                        default=dict, help_text="Query parameters for data fetching"
                    ),
                ),
                (
                    "display_config",
                    models.JSONField(
                        default=dict,
                        help_text="Display settings (colors, labels, etc.)",
                    ),
                ),
                (
                    "refresh_interval",
                    models.IntegerField(
                        default=300, help_text="Refresh interval in seconds"
                    ),
                ),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                (
                    "width",
                    models.IntegerField(default=4, help_text="Grid width (1-12)"),
                ),
                (
                    "height",
                    models.IntegerField(default=4, help_text="Grid height units"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="advanced_reporting.dashboard",
                    ),
                ),
            ],
            options={
                "db_table": "crm_dashboard_widget",
                "ordering": ["dashboard", "order"],
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "kpi_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue"),
                            ("conversion_rate", "Conversion Rate"),
                            ("win_rate", "Win Rate"),
                            ("average_deal_size", "Average Deal Size"),
                            ("sales_cycle_length", "Sales Cycle Length"),
                            ("lead_response_time", "Lead Response Time"),
                            ("customer_acquisition_cost", "Customer Acquisition Cost"),
                            ("custom", "Custom KPI"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "calculation_formula",
                    models.TextField(help_text="Python expression or query"),
                ),
                ("data_source", models.JSONField(default=dict)),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="number",
                        help_text="e.g., currency, percentage",
                        max_length=50,
                    ),
                ),
                ("display_format", models.CharField(default="number", max_length=50)),
                ("color_good", models.CharField(default="#10B981", max_length=7)),
                ("color_warning", models.CharField(default="#F59E0B", max_length=7)),
                ("color_bad", models.CharField(default="#EF4444", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "crm_kpi",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KPIValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "previous_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "change_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Additional context"),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="advanced_reporting.kpi",
                    ),
                ),
            ],
            options={
                "db_table": "crm_kpi_value",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales_performance", "Sales Performance"),
                            ("lead_analysis", "Lead Analysis"),
                            ("pipeline_forecast", "Pipeline Forecast"),
                            ("campaign_roi", "Campaign ROI"),
                            ("team_productivity", "Team Productivity"),
                            ("revenue_analysis", "Revenue Analysis"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "data_sources",
                    models.JSONField(default=list, help_text="List of data sources"),
                ),
                ("filters", models.JSONField(default=dict, help_text="Report filters")),
                (
                    "columns",
                    models.JSONField(default=list, help_text="Columns to include"),
                ),
                (
                    "grouping",
                    models.JSONField(default=list, help_text="Group by fields"),
                ),
                ("sorting", models.JSONField(default=list, help_text="Sort order")),
                (
                    "calculations",
                    models.JSONField(
                        default=dict, help_text="Calculations and aggregations"
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                ("include_charts", models.BooleanField(default=True)),
                ("include_summary", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_generated_at", models.DateTimeField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="advanced_shared_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "crm_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("teams", "Microsoft Teams"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "schedule_time",
                    models.TimeField(help_text="Time to send (24-hour format)"),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True, help_text="0=Monday, 6=Sunday"
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(blank=True, help_text="1-31"),
                ),
                (
                    "recipients",
                    models.JSONField(
                        default=list, help_text="Email addresses or user IDs"
                    ),
                ),
                (
                    "delivery_config",
                    models.JSONField(
                        default=dict, help_text="Additional delivery settings"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sent_at", models.DateTimeField(blank=True)),
                ("next_run_at", models.DateTimeField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="advanced_reporting.report",
                    ),
                ),
            ],
            options={
                "db_table": "crm_report_schedule",
                "ordering": ["next_run_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("filters_used", models.JSONField(default=dict)),
                ("rows_returned", models.IntegerField(blank=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size_bytes", models.BigIntegerField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="advanced_reporting.report",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="advanced_reporting.reportschedule",
                    ),
                ),
            ],
            options={
                "db_table": "crm_report_execution",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["owner", "dashboard_type"],
                name="crm_dashboa_owner_i_e6d181_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["is_default", "is_public"],
                name="crm_dashboa_is_defa_336737_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardwidget",
            index=models.Index(
                fields=["dashboard", "is_active"], name="crm_dashboa_dashboa_2a397c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kpi",
            index=models.Index(
                fields=["kpi_type", "is_active"], name="crm_kpi_kpi_typ_5c8531_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kpi",
            index=models.Index(fields=["owner"], name="crm_kpi_owner_i_fd1452_idx"),
        ),
        migrations.AddIndex(
            model_name="kpivalue",
            index=models.Index(
                fields=["kpi", "-period_end"], name="crm_kpi_val_kpi_id_864303_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kpivalue",
            unique_together={("kpi", "period_start", "period_end")},
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["owner", "report_type"], name="crm_report_owner_i_d9c3ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["is_public"], name="crm_report_is_publ_bbb097_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["is_active", "next_run_at"],
                name="crm_report__is_acti_b821f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["report"], name="crm_report__report__70a09f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["report", "-started_at"], name="crm_report__report__99b567_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(fields=["status"], name="crm_report__status_27b61e_idx"),
        ),
    ]
