# Generated by Django 5.2.7 on 2025-11-23 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact_management", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("model_version", models.CharField(max_length=50)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("accuracy", "Accuracy"),
                            ("precision", "Precision"),
                            ("recall", "Recall"),
                            ("f1_score", "F1 Score"),
                            ("auc_roc", "AUC-ROC"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metric_value", models.FloatField()),
                ("sample_size", models.IntegerField()),
                ("measured_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "AI Model Metrics",
                "verbose_name_plural": "AI Model Metrics",
                "ordering": ["-measured_at"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "-measured_at"],
                        name="ai_insights_model_n_deffe5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("call", "Call Transcript"),
                            ("chat", "Chat Message"),
                            ("note", "Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.IntegerField()),
                ("text_content", models.TextField()),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("very_negative", "Very Negative"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                            ("positive", "Positive"),
                            ("very_positive", "Very Positive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(help_text="Sentiment score (-1 to 1)"),
                ),
                (
                    "confidence",
                    models.FloatField(help_text="Analysis confidence (0-1)"),
                ),
                (
                    "emotions",
                    models.JSONField(default=dict, help_text="Emotion breakdown"),
                ),
                (
                    "keywords",
                    models.JSONField(default=list, help_text="Key phrases extracted"),
                ),
                (
                    "topics",
                    models.JSONField(default=list, help_text="Topics identified"),
                ),
                ("requires_attention", models.BooleanField(default=False)),
                ("alert_reason", models.TextField(blank=True)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sentiment Analysis",
                "verbose_name_plural": "Sentiment Analyses",
                "ordering": ["-analyzed_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="ai_insights_entity__d9b323_idx",
                    ),
                    models.Index(
                        fields=["sentiment", "-analyzed_at"],
                        name="ai_insights_sentime_186200_idx",
                    ),
                    models.Index(
                        fields=["requires_attention"],
                        name="ai_insights_require_34dad5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIGeneratedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("social", "Social Media"),
                            ("proposal", "Proposal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField(help_text="User's input prompt")),
                (
                    "context_data",
                    models.JSONField(
                        default=dict, help_text="Context used for generation"
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("body", models.TextField()),
                ("tone", models.CharField(default="professional", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("quality_score", models.FloatField(blank=True)),
                ("readability_score", models.FloatField(blank=True)),
                ("was_used", models.BooleanField(default=False)),
                ("was_edited", models.BooleanField(default=False)),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True, help_text="1-5 star rating"
                    ),
                ),
                (
                    "model_used",
                    models.CharField(default="gpt-3.5-turbo", max_length=100),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Generated Content",
                "verbose_name_plural": "AI Generated Content",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ai_insights_user_id_2e5c60_idx",
                    ),
                    models.Index(
                        fields=["content_type", "-created_at"],
                        name="ai_insights_content_6b5a2c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChurnPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "churn_probability",
                    models.FloatField(help_text="Probability of churn (0-1)"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "factors",
                    models.JSONField(
                        default=dict, help_text="Factors contributing to prediction"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(help_text="Model confidence (0-1)"),
                ),
                ("recommended_actions", models.JSONField(default=list)),
                ("model_version", models.CharField(max_length=50)),
                ("predicted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When prediction becomes stale"),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="churn_predictions",
                        to="contact_management.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Churn Prediction",
                "verbose_name_plural": "Churn Predictions",
                "ordering": ["-predicted_at"],
                "indexes": [
                    models.Index(
                        fields=["contact", "-predicted_at"],
                        name="ai_insights_contact_fa49a4_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "-predicted_at"],
                        name="ai_insights_risk_le_20043b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NextBestAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("contact", "Contact"),
                            ("opportunity", "Opportunity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.IntegerField()),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("call", "Schedule Call"),
                            ("email", "Send Email"),
                            ("meeting", "Schedule Meeting"),
                            ("follow_up", "Follow Up"),
                            ("proposal", "Send Proposal"),
                            ("discount", "Offer Discount"),
                            ("upsell", "Upsell Opportunity"),
                            ("check_in", "Customer Check-in"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "reasoning",
                    models.TextField(help_text="Why this action is recommended"),
                ),
                (
                    "priority_score",
                    models.FloatField(help_text="Priority score (0-100)"),
                ),
                (
                    "expected_impact",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("suggested_timing", models.DateTimeField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("dismissed", "Dismissed"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("model_version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Next Best Action",
                "verbose_name_plural": "Next Best Actions",
                "ordering": ["-priority_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-priority_score"],
                        name="ai_insights_user_id_552d26_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="ai_insights_entity__e0df71_idx",
                    ),
                ],
            },
        ),
    ]
