# Generated by Django 5.2.7 on 2026-01-24 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpaceEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("earth", "Earth"),
                            ("moon", "Moon"),
                            ("mars", "Mars"),
                            ("iss", "International Space Station"),
                            ("satellite", "Satellite"),
                        ],
                        max_length=100,
                    ),
                ),
                ("latency_seconds", models.IntegerField()),
                ("connection_type", models.CharField(max_length=50)),
                ("is_online", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["latency_seconds"],
            },
        ),
        migrations.CreateModel(
            name="OfflineDataCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("data_type", models.CharField(max_length=100)),
                ("data", models.JSONField(default=dict)),
                ("version", models.IntegerField(default=1)),
                ("synced", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interplanetary_sync.spaceendpoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DelayTolerantMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("message_type", models.CharField(max_length=100)),
                ("payload", models.JSONField(default=dict)),
                ("priority", models.IntegerField(default=5)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True)),
                ("status", models.CharField(default="queued", max_length=20)),
                (
                    "encryption_type",
                    models.CharField(default="satellite_optimized", max_length=50),
                ),
                (
                    "from_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="interplanetary_sync.spaceendpoint",
                    ),
                ),
                (
                    "to_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="interplanetary_sync.spaceendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "sent_at"],
            },
        ),
    ]
