# Generated by Django 6.0 on 2025-12-28 08:38

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact_management", "0002_initial"),
        ("opportunity_management", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendeeIntelligence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("preferred_meeting_times", models.JSONField(default=list)),
                ("response_time_average", models.DurationField(null=True)),
                ("typical_response_days", models.JSONField(default=list)),
                ("total_meetings_scheduled", models.IntegerField(default=0)),
                ("meetings_attended", models.IntegerField(default=0)),
                ("meetings_no_show", models.IntegerField(default=0)),
                ("meetings_cancelled", models.IntegerField(default=0)),
                ("meetings_rescheduled", models.IntegerField(default=0)),
                ("average_meeting_duration", models.IntegerField(null=True)),
                ("prefers_video", models.BooleanField(null=True)),
                ("prefers_phone", models.BooleanField(null=True)),
                ("detected_timezone", models.CharField(blank=True, max_length=50)),
                ("timezone_confidence", models.FloatField(default=0.0)),
                ("reminder_response_rate", models.FloatField(null=True)),
                (
                    "best_reminder_timing",
                    models.IntegerField(help_text="Minutes before", null=True),
                ),
                (
                    "best_communication_channel",
                    models.CharField(blank=True, max_length=20),
                ),
                ("reliability_score", models.FloatField(default=0.5)),
                ("engagement_score", models.FloatField(default=0.5)),
                ("last_meeting_at", models.DateTimeField(null=True)),
                ("last_interaction_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "attendee_intelligence",
            },
        ),
        migrations.CreateModel(
            name="MeetingType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(480),
                        ],
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("video_zoom", "Zoom"),
                            ("video_meet", "Google Meet"),
                            ("video_teams", "Microsoft Teams"),
                            ("phone", "Phone Call"),
                            ("in_person", "In Person"),
                            ("custom", "Custom Location"),
                        ],
                        default="video_zoom",
                        max_length=50,
                    ),
                ),
                ("location_details", models.TextField(blank=True)),
                (
                    "buffer_before",
                    models.IntegerField(default=0, help_text="Minutes before meeting"),
                ),
                (
                    "buffer_after",
                    models.IntegerField(default=0, help_text="Minutes after meeting"),
                ),
                (
                    "min_notice_hours",
                    models.IntegerField(
                        default=24, help_text="Minimum hours in advance"
                    ),
                ),
                (
                    "max_future_days",
                    models.IntegerField(default=60, help_text="Max days in future"),
                ),
                (
                    "max_per_day",
                    models.IntegerField(
                        blank=True, help_text="Max bookings per day", null=True
                    ),
                ),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                (
                    "custom_questions",
                    models.JSONField(
                        default=list, help_text="Questions to ask when booking"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("bookings_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "meeting_types",
                "ordering": ["duration_minutes", "name"],
            },
        ),
        migrations.CreateModel(
            name="AISchedulingPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preferred_meeting_times",
                    models.JSONField(
                        default=dict, help_text="Hour -> preference score mapping"
                    ),
                ),
                (
                    "preferred_days",
                    models.JSONField(
                        default=dict, help_text="Day of week -> preference score"
                    ),
                ),
                ("preferred_meeting_duration", models.IntegerField(default=30)),
                ("max_meetings_per_day", models.IntegerField(default=8)),
                ("max_consecutive_meetings", models.IntegerField(default=3)),
                ("focus_time_start", models.TimeField(blank=True, null=True)),
                ("focus_time_end", models.TimeField(blank=True, null=True)),
                (
                    "focus_days",
                    models.JSONField(
                        default=list, help_text="Days to protect focus time"
                    ),
                ),
                ("high_energy_hours", models.JSONField(default=list)),
                ("low_energy_hours", models.JSONField(default=list)),
                (
                    "meeting_type_preferences",
                    models.JSONField(
                        default=dict, help_text="Meeting type -> preferred time/day"
                    ),
                ),
                ("min_gap_between_meetings", models.IntegerField(default=15)),
                ("prefer_batched_meetings", models.BooleanField(default=False)),
                ("batch_meeting_days", models.JSONField(default=list)),
                ("data_points_count", models.IntegerField(default=0)),
                ("last_learning_at", models.DateTimeField(blank=True, null=True)),
                ("preference_confidence", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_scheduling_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_scheduling_preferences",
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("guest_name", models.CharField(max_length=200)),
                ("guest_email", models.EmailField(max_length=254)),
                ("guest_phone", models.CharField(blank=True, max_length=50)),
                ("guest_timezone", models.CharField(default="UTC", max_length=50)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("location", models.TextField(blank=True)),
                ("video_link", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("custom_answers", models.JSONField(default=dict)),
                ("cancel_token", models.CharField(max_length=64, unique=True)),
                ("reschedule_token", models.CharField(max_length=64, unique=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_24h_sent", models.BooleanField(default=False)),
                ("reminder_1h_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="contact_management.contact",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="opportunity_management.opportunity",
                    ),
                ),
                (
                    "meeting_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="smart_scheduling.meetingtype",
                    ),
                ),
            ],
            options={
                "db_table": "scheduled_meetings",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="MeetingPrepAI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("participant_summary", models.TextField(blank=True)),
                ("company_info", models.JSONField(default=dict)),
                ("linkedin_data", models.JSONField(default=dict)),
                ("recent_news", models.JSONField(default=list)),
                ("crm_contact_summary", models.TextField(blank=True)),
                ("previous_interactions", models.JSONField(default=list)),
                ("open_opportunities", models.JSONField(default=list)),
                ("pending_tasks", models.JSONField(default=list)),
                ("meeting_history_with_contact", models.JSONField(default=list)),
                ("last_meeting_summary", models.TextField(blank=True)),
                ("last_meeting_action_items", models.JSONField(default=list)),
                ("suggested_agenda", models.JSONField(default=list)),
                ("talking_points", models.JSONField(default=list)),
                ("questions_to_ask", models.JSONField(default=list)),
                ("potential_objections", models.JSONField(default=list)),
                ("personalization_tips", models.JSONField(default=list)),
                ("ice_breakers", models.JSONField(default=list)),
                ("mutual_connections", models.JSONField(default=list)),
                ("deal_stage", models.CharField(blank=True, max_length=100)),
                (
                    "deal_value",
                    models.DecimalField(decimal_places=2, max_digits=15, null=True),
                ),
                ("win_probability", models.FloatField(null=True)),
                ("recommended_next_steps", models.JSONField(default=list)),
                ("prep_generated_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("was_helpful", models.BooleanField(null=True)),
                ("feedback", models.TextField(blank=True)),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_prep",
                        to="smart_scheduling.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_prep_ai",
            },
        ),
        migrations.CreateModel(
            name="MeetingReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("notification", "Push Notification"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "minutes_before",
                    models.IntegerField(
                        choices=[
                            (1440, "24 hours before"),
                            (60, "1 hour before"),
                            (30, "30 minutes before"),
                            (15, "15 minutes before"),
                        ],
                        default=60,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("for_guest", models.BooleanField(default=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="smart_scheduling.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_reminders",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="AITimeSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("optimal", "Optimal Time"),
                            ("alternative", "Alternative Time"),
                            ("reschedule", "Reschedule Suggestion"),
                            ("batch", "Batch Meeting"),
                        ],
                        default="optimal",
                        max_length=20,
                    ),
                ),
                ("suggested_start", models.DateTimeField()),
                ("suggested_end", models.DateTimeField()),
                (
                    "overall_score",
                    models.FloatField(default=0.0, help_text="0-100 score"),
                ),
                ("preference_score", models.FloatField(default=0.0)),
                ("availability_score", models.FloatField(default=0.0)),
                ("energy_score", models.FloatField(default=0.0)),
                ("context_switch_score", models.FloatField(default=0.0)),
                ("reasoning", models.TextField(blank=True)),
                ("factors", models.JSONField(default=dict)),
                ("participant_email", models.EmailField(blank=True, max_length=254)),
                ("participant_timezone", models.CharField(blank=True, max_length=50)),
                ("mutual_availability", models.JSONField(default=list)),
                ("was_accepted", models.BooleanField(null=True)),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_time_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestions",
                        to="smart_scheduling.meetingtype",
                    ),
                ),
            ],
            options={
                "db_table": "ai_time_suggestions",
                "ordering": ["-overall_score"],
            },
        ),
        migrations.CreateModel(
            name="NoShowPrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "no_show_probability",
                    models.FloatField(default=0.0, help_text="0-1 probability"),
                ),
                ("prediction_confidence", models.FloatField(default=0.0)),
                ("risk_factors", models.JSONField(default=list)),
                (
                    "risk_score",
                    models.IntegerField(default=0, help_text="0-100 risk score"),
                ),
                ("guest_meeting_history", models.JSONField(default=dict)),
                ("historical_no_show_rate", models.FloatField(null=True)),
                ("days_until_meeting", models.IntegerField(null=True)),
                ("meeting_time_of_day", models.CharField(blank=True, max_length=20)),
                ("day_of_week", models.IntegerField(null=True)),
                ("email_open_rate", models.FloatField(null=True)),
                ("previous_reschedules", models.IntegerField(default=0)),
                ("confirmation_sent", models.BooleanField(default=False)),
                ("confirmation_opened", models.BooleanField(default=False)),
                ("recommended_actions", models.JSONField(default=list)),
                ("extra_reminder_suggested", models.BooleanField(default=False)),
                ("confirmation_call_suggested", models.BooleanField(default=False)),
                ("actual_outcome", models.CharField(blank=True, max_length=20)),
                ("prediction_was_correct", models.BooleanField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="no_show_prediction",
                        to="smart_scheduling.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "no_show_predictions",
            },
        ),
        migrations.CreateModel(
            name="ScheduleOptimization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "optimization_type",
                    models.CharField(
                        choices=[
                            ("batch_meetings", "Batch Similar Meetings"),
                            ("create_focus_time", "Create Focus Time"),
                            ("reduce_context_switch", "Reduce Context Switching"),
                            ("energy_alignment", "Align with Energy Levels"),
                            ("travel_optimization", "Optimize for Travel"),
                        ],
                        max_length=30,
                    ),
                ),
                ("analysis_start", models.DateField()),
                ("analysis_end", models.DateField()),
                ("current_schedule", models.JSONField(default=list)),
                ("current_metrics", models.JSONField(default=dict)),
                ("optimized_schedule", models.JSONField(default=list)),
                ("optimized_metrics", models.JSONField(default=dict)),
                ("meetings_affected", models.IntegerField(default=0)),
                ("time_saved_minutes", models.IntegerField(default=0)),
                ("focus_time_gained_minutes", models.IntegerField(default=0)),
                ("context_switches_reduced", models.IntegerField(default=0)),
                ("current_score", models.FloatField(default=0.0)),
                ("optimized_score", models.FloatField(default=0.0)),
                ("improvement_percentage", models.FloatField(default=0.0)),
                ("recommendations", models.JSONField(default=list)),
                ("explanation", models.TextField(blank=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("applied", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_optimizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "schedule_optimizations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchedulingPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("welcome_message", models.TextField(default="Book a time with me")),
                ("logo", models.URLField(blank=True)),
                ("brand_color", models.CharField(default="#3B82F6", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("require_approval", models.BooleanField(default=False)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("page_views", models.IntegerField(default=0)),
                ("bookings_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduling_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scheduling_pages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchedulingAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("page_views", models.IntegerField(default=0)),
                ("unique_visitors", models.IntegerField(default=0)),
                ("bookings_created", models.IntegerField(default=0)),
                ("bookings_cancelled", models.IntegerField(default=0)),
                ("bookings_rescheduled", models.IntegerField(default=0)),
                ("bookings_completed", models.IntegerField(default=0)),
                ("bookings_no_show", models.IntegerField(default=0)),
                ("bookings_by_type", models.JSONField(default=dict)),
                ("peak_booking_hour", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="smart_scheduling.schedulingpage",
                    ),
                ),
            ],
            options={
                "db_table": "scheduling_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="meetingtype",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_types",
                to="smart_scheduling.schedulingpage",
            ),
        ),
        migrations.CreateModel(
            name="BlockedTime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("is_recurring", models.BooleanField(default=False)),
                ("recurrence_rule", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_times",
                        to="smart_scheduling.schedulingpage",
                    ),
                ),
            ],
            options={
                "db_table": "blocked_times",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="smart_scheduling.schedulingpage",
                    ),
                ),
            ],
            options={
                "db_table": "scheduling_availability",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="SmartReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("minutes_before", models.IntegerField()),
                ("is_ai_optimized", models.BooleanField(default=False)),
                ("optimization_reason", models.TextField(blank=True)),
                (
                    "optimal_channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("slack", "Slack"),
                            ("teams", "MS Teams"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("channel_preference_score", models.JSONField(default=dict)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("include_prep_material", models.BooleanField(default=False)),
                ("include_agenda", models.BooleanField(default=False)),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(null=True)),
                ("delivery_status", models.CharField(blank=True, max_length=50)),
                ("opened", models.BooleanField(default=False)),
                ("opened_at", models.DateTimeField(null=True)),
                ("clicked", models.BooleanField(default=False)),
                ("clicked_at", models.DateTimeField(null=True)),
                ("recipient_type", models.CharField(default="guest", max_length=20)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_reminders",
                        to="smart_scheduling.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "smart_reminders",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartReschedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("conflict", "Calendar Conflict"),
                            ("optimization", "Schedule Optimization"),
                            ("no_show_risk", "High No-Show Risk"),
                            ("user_request", "User Request"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trigger_reason", models.TextField(blank=True)),
                ("original_start", models.DateTimeField()),
                ("original_end", models.DateTimeField()),
                (
                    "alternatives",
                    models.JSONField(
                        default=list, help_text="List of alternative time slots"
                    ),
                ),
                ("suggested_start", models.DateTimeField(null=True)),
                ("suggested_end", models.DateTimeField(null=True)),
                ("suggestion_score", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("suggested", "Suggested to Participants"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(null=True)),
                ("host_notified", models.BooleanField(default=False)),
                ("guest_notified", models.BooleanField(default=False)),
                ("response_by", models.CharField(blank=True, max_length=20)),
                ("selected_alternative", models.JSONField(null=True)),
                ("response_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reschedule_suggestions",
                        to="smart_scheduling.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "smart_reschedule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CalendarIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google Calendar"),
                            ("outlook", "Outlook Calendar"),
                            ("apple", "Apple Calendar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(null=True)),
                ("calendar_id", models.CharField(default="primary", max_length=200)),
                ("calendar_name", models.CharField(blank=True, max_length=200)),
                ("sync_enabled", models.BooleanField(default=True)),
                ("check_conflicts", models.BooleanField(default=True)),
                ("create_events", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "calendar_integrations",
                "unique_together": {("user", "provider")},
            },
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["host", "start_time"], name="scheduled_m_host_id_4ecdb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["guest_email"], name="scheduled_m_guest_e_d2ce7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(fields=["status"], name="scheduled_m_status_79b712_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="schedulinganalytics",
            unique_together={("page", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="meetingtype",
            unique_together={("page", "slug")},
        ),
    ]
