# Generated by Django 5.2.7 on 2025-11-23 05:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_feed", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("email_mentions", models.BooleanField(default=True)),
                ("email_assignments", models.BooleanField(default=True)),
                ("email_comments", models.BooleanField(default=True)),
                ("email_updates", models.BooleanField(default=False)),
                ("email_daily_digest", models.BooleanField(default=False)),
                ("email_weekly_digest", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("push_mentions", models.BooleanField(default=True)),
                ("push_assignments", models.BooleanField(default=True)),
                ("push_comments", models.BooleanField(default=False)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("in_app_mentions", models.BooleanField(default=True)),
                ("in_app_assignments", models.BooleanField(default=True)),
                ("in_app_comments", models.BooleanField(default=True)),
                ("in_app_updates", models.BooleanField(default=True)),
                (
                    "digest_time",
                    models.TimeField(
                        default="08:00:00", help_text="Time to send daily digest"
                    ),
                ),
                (
                    "digest_day",
                    models.IntegerField(
                        default=1, help_text="Day of week for weekly digest (0=Monday)"
                    ),
                ),
                ("dnd_enabled", models.BooleanField(default=False)),
                ("dnd_start_time", models.TimeField(blank=True, null=True)),
                ("dnd_end_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "crm_notification_preferences",
            },
        ),
    ]
