# Generated by Django 6.0 on 2026-01-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_feed", "0002_notificationpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="object_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
