# Generated by Django 6.0 on 2025-12-28 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact_management", "0002_initial"),
        ("lead_management", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyEnrichment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=300)),
                ("legal_name", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=200)),
                ("sub_industry", models.CharField(blank=True, max_length=200)),
                (
                    "industry_codes",
                    models.JSONField(default=dict, help_text="SIC, NAICS codes"),
                ),
                ("sector", models.CharField(blank=True, max_length=100)),
                ("employee_count", models.IntegerField(blank=True, null=True)),
                (
                    "employee_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-10", "1-10 employees"),
                            ("11-50", "11-50 employees"),
                            ("51-200", "51-200 employees"),
                            ("201-500", "201-500 employees"),
                            ("501-1000", "501-1000 employees"),
                            ("1001-5000", "1001-5000 employees"),
                            ("5001-10000", "5001-10000 employees"),
                            ("10000+", "10000+ employees"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("revenue_range", models.CharField(blank=True, max_length=100)),
                (
                    "funding_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("funding_rounds", models.JSONField(default=list)),
                ("headquarters_address", models.TextField(blank=True)),
                ("headquarters_city", models.CharField(blank=True, max_length=100)),
                ("headquarters_state", models.CharField(blank=True, max_length=100)),
                ("headquarters_country", models.CharField(blank=True, max_length=100)),
                (
                    "headquarters_postal_code",
                    models.CharField(blank=True, max_length=20),
                ),
                ("office_locations", models.JSONField(default=list)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "email_patterns",
                    models.JSONField(default=list, help_text="Common email patterns"),
                ),
                ("website", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("crunchbase_url", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("brand_colors", models.JSONField(default=list)),
                ("ceo_name", models.CharField(blank=True, max_length=200)),
                ("key_people", models.JSONField(default=list)),
                ("technologies", models.JSONField(default=list)),
                ("tech_categories", models.JSONField(default=dict)),
                ("alexa_rank", models.IntegerField(blank=True, null=True)),
                ("monthly_visits", models.BigIntegerField(blank=True, null=True)),
                ("traffic_rank", models.IntegerField(blank=True, null=True)),
                ("enrichment_score", models.IntegerField(default=0)),
                ("last_enriched_at", models.DateTimeField(blank=True, null=True)),
                ("enrichment_sources", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Company Enrichments",
                "db_table": "company_enrichments",
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("risky", "Risky"),
                            ("unknown", "Unknown"),
                            ("catch_all", "Catch-All"),
                            ("disposable", "Disposable"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("is_deliverable", models.BooleanField(null=True)),
                ("is_smtp_valid", models.BooleanField(null=True)),
                ("is_free_email", models.BooleanField(null=True)),
                ("is_role_email", models.BooleanField(null=True)),
                ("is_disposable", models.BooleanField(null=True)),
                ("is_catch_all", models.BooleanField(null=True)),
                ("domain", models.CharField(max_length=255)),
                ("mx_records", models.JSONField(default=list)),
                ("has_mx_records", models.BooleanField(null=True)),
                (
                    "quality_score",
                    models.FloatField(default=0.0, help_text="0-1 quality score"),
                ),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                ("verification_provider", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "email_verifications",
            },
        ),
        migrations.CreateModel(
            name="EnrichmentProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("clearbit", "Clearbit"),
                            ("zoominfo", "ZoomInfo"),
                            ("linkedin", "LinkedIn Sales Navigator"),
                            ("apollo", "Apollo.io"),
                            ("hunter", "Hunter.io"),
                            ("fullcontact", "FullContact"),
                            ("pipl", "Pipl"),
                            ("builtwith", "BuiltWith"),
                            ("similarweb", "SimilarWeb"),
                            ("crunchbase", "Crunchbase"),
                            ("glassdoor", "Glassdoor"),
                            ("news_api", "News API"),
                            ("custom", "Custom API"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "api_key",
                    models.TextField(blank=True, help_text="Encrypted API key"),
                ),
                (
                    "api_secret",
                    models.TextField(blank=True, help_text="Encrypted API secret"),
                ),
                ("api_endpoint", models.URLField(blank=True)),
                ("requests_per_minute", models.IntegerField(default=60)),
                ("requests_per_day", models.IntegerField(default=10000)),
                ("daily_requests_used", models.IntegerField(default=0)),
                ("last_request_reset", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_configured", models.BooleanField(default=False)),
                ("can_enrich_person", models.BooleanField(default=True)),
                ("can_enrich_company", models.BooleanField(default=True)),
                ("can_find_email", models.BooleanField(default=False)),
                ("can_verify_email", models.BooleanField(default=False)),
                ("can_get_technographics", models.BooleanField(default=False)),
                ("can_get_intent", models.BooleanField(default=False)),
                ("total_requests", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                ("average_response_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "enrichment_providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EnrichmentJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Record"),
                            ("bulk", "Bulk Import"),
                            ("scheduled", "Scheduled Refresh"),
                            ("webhook", "Webhook Trigger"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partially Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("processed_records", models.IntegerField(default=0)),
                ("successful_records", models.IntegerField(default=0)),
                ("failed_records", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrichment_types",
                    models.JSONField(
                        default=list, help_text="Types of enrichment to perform"
                    ),
                ),
                ("providers_used", models.JSONField(default=list)),
                ("results_summary", models.JSONField(default=dict)),
                ("error_log", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrichment_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "enrichment_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrichmentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("domain", models.CharField(blank=True, db_index=True, max_length=255)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Enrichment"),
                            ("enriching", "Enriching"),
                            ("enriched", "Enriched"),
                            ("partial", "Partially Enriched"),
                            ("failed", "Enrichment Failed"),
                            ("stale", "Data Stale"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "enrichment_score",
                    models.IntegerField(
                        default=0, help_text="0-100 completeness score"
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("seniority", models.CharField(blank=True, max_length=50)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("mobile_phone", models.CharField(blank=True, max_length=50)),
                ("work_email", models.EmailField(blank=True, max_length=254)),
                ("personal_email", models.EmailField(blank=True, max_length=254)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("timezone", models.CharField(blank=True, max_length=50)),
                ("linkedin_profile", models.JSONField(default=dict)),
                ("twitter_handle", models.CharField(blank=True, max_length=100)),
                ("github_username", models.CharField(blank=True, max_length=100)),
                ("employment_history", models.JSONField(default=list)),
                ("education", models.JSONField(default=list)),
                ("skills", models.JSONField(default=list)),
                ("last_enriched_at", models.DateTimeField(blank=True, null=True)),
                ("enrichment_sources", models.JSONField(default=list)),
                ("data_freshness_score", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_profile",
                        to="contact_management.contact",
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_profile",
                        to="lead_management.lead",
                    ),
                ),
            ],
            options={
                "db_table": "enrichment_profiles",
            },
        ),
        migrations.CreateModel(
            name="EnrichmentActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("enrich_person", "Person Enrichment"),
                            ("enrich_company", "Company Enrichment"),
                            ("verify_email", "Email Verification"),
                            ("get_technographics", "Technographics"),
                            ("get_intent", "Intent Signal"),
                            ("get_news", "News Alert"),
                            ("get_social", "Social Profile"),
                            ("get_financial", "Financial Data"),
                        ],
                        max_length=50,
                    ),
                ),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("fields_enriched", models.JSONField(default=list)),
                ("data_returned", models.JSONField(default=dict)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("api_credits_used", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="data_enrichment.companyenrichment",
                    ),
                ),
                (
                    "enrichment_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="data_enrichment.enrichmentprofile",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data_enrichment.enrichmentprovider",
                    ),
                ),
            ],
            options={
                "db_table": "enrichment_activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrichmentRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("new_lead", "New Lead Created"),
                            ("new_contact", "New Contact Created"),
                            ("email_received", "Email Received"),
                            ("form_submit", "Form Submission"),
                            ("import", "Data Import"),
                            ("schedule", "Scheduled"),
                            ("manual", "Manual Trigger"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict, help_text="Conditions for rule to apply"
                    ),
                ),
                ("enrich_person", models.BooleanField(default=True)),
                ("enrich_company", models.BooleanField(default=True)),
                ("verify_email", models.BooleanField(default=True)),
                ("get_technographics", models.BooleanField(default=False)),
                ("get_intent", models.BooleanField(default=False)),
                ("get_news", models.BooleanField(default=False)),
                ("preferred_providers", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("times_triggered", models.IntegerField(default=0)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrichment_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "enrichment_rules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("revenue_currency", models.CharField(default="USD", max_length=3)),
                ("revenue_year", models.IntegerField(blank=True, null=True)),
                ("revenue_growth_rate", models.FloatField(blank=True, null=True)),
                (
                    "total_funding",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("last_funding_round", models.CharField(blank=True, max_length=50)),
                (
                    "last_funding_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("last_funding_date", models.DateField(blank=True, null=True)),
                ("investors", models.JSONField(default=list)),
                (
                    "estimated_valuation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("valuation_date", models.DateField(blank=True, null=True)),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("stock_symbol", models.CharField(blank=True, max_length=10)),
                ("stock_exchange", models.CharField(blank=True, max_length=20)),
                ("credit_rating", models.CharField(blank=True, max_length=20)),
                ("risk_score", models.IntegerField(blank=True, null=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("data_source", models.CharField(blank=True, max_length=100)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_data",
                        to="data_enrichment.companyenrichment",
                    ),
                ),
            ],
            options={
                "db_table": "financial_data",
            },
        ),
        migrations.CreateModel(
            name="IntentSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "intent_type",
                    models.CharField(
                        choices=[
                            ("search", "Search Intent"),
                            ("content", "Content Consumption"),
                            ("comparison", "Comparison Shopping"),
                            ("review", "Review Research"),
                            ("social", "Social Engagement"),
                            ("job_posting", "Job Posting"),
                            ("tech_install", "Technology Install"),
                            ("funding", "Funding Event"),
                            ("expansion", "Expansion Signal"),
                        ],
                        max_length=50,
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("topic_category", models.CharField(blank=True, max_length=100)),
                (
                    "strength",
                    models.CharField(
                        choices=[
                            ("weak", "Weak"),
                            ("moderate", "Moderate"),
                            ("strong", "Strong"),
                            ("very_strong", "Very Strong"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(default=50, help_text="0-100 intent score"),
                ),
                ("description", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("source_url", models.URLField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("was_actioned", models.BooleanField(default=False)),
                ("actioned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actioned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actioned_intent_signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intent_signals",
                        to="data_enrichment.companyenrichment",
                    ),
                ),
                (
                    "enrichment_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intent_signals",
                        to="data_enrichment.enrichmentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "intent_signals",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("funding", "Funding Round"),
                            ("acquisition", "Acquisition"),
                            ("ipo", "IPO"),
                            ("executive_change", "Executive Change"),
                            ("expansion", "Expansion/New Office"),
                            ("product_launch", "Product Launch"),
                            ("partnership", "Partnership"),
                            ("layoff", "Layoffs/Restructuring"),
                            ("award", "Award/Recognition"),
                            ("earnings", "Earnings Report"),
                            ("legal", "Legal/Regulatory"),
                            ("general", "General News"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True)),
                ("full_content", models.TextField(blank=True)),
                ("source_name", models.CharField(blank=True, max_length=200)),
                ("source_url", models.URLField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("relevance_score", models.FloatField(default=0.5)),
                ("people_mentioned", models.JSONField(default=list)),
                ("companies_mentioned", models.JSONField(default=list)),
                ("amounts_mentioned", models.JSONField(default=list)),
                ("is_sales_trigger", models.BooleanField(default=False)),
                ("trigger_reason", models.TextField(blank=True)),
                ("recommended_action", models.TextField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_alerts",
                        to="data_enrichment.companyenrichment",
                    ),
                ),
                (
                    "read_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="read_news_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "news_alerts",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter"),
                            ("github", "GitHub"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("medium", "Medium"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("profile_url", models.URLField()),
                ("username", models.CharField(blank=True, max_length=200)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("headline", models.TextField(blank=True)),
                ("bio", models.TextField(blank=True)),
                ("avatar_url", models.URLField(blank=True)),
                ("followers_count", models.IntegerField(blank=True, null=True)),
                ("following_count", models.IntegerField(blank=True, null=True)),
                ("connections_count", models.IntegerField(blank=True, null=True)),
                ("posts_count", models.IntegerField(blank=True, null=True)),
                ("last_active", models.DateTimeField(blank=True, null=True)),
                ("recent_posts", models.JSONField(default=list)),
                ("interests", models.JSONField(default=list)),
                ("engagement_rate", models.FloatField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "enrichment_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_profiles",
                        to="data_enrichment.enrichmentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "social_profiles",
            },
        ),
        migrations.CreateModel(
            name="TechnographicData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("technology_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("analytics", "Analytics"),
                            ("advertising", "Advertising"),
                            ("cms", "CMS"),
                            ("crm", "CRM"),
                            ("ecommerce", "E-commerce"),
                            ("email", "Email Marketing"),
                            ("framework", "Framework"),
                            ("hosting", "Hosting"),
                            ("language", "Programming Language"),
                            ("marketing_automation", "Marketing Automation"),
                            ("payment", "Payment"),
                            ("security", "Security"),
                            ("social", "Social Media"),
                            ("support", "Customer Support"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=50)),
                ("first_detected", models.DateTimeField(auto_now_add=True)),
                ("last_detected", models.DateTimeField(auto_now=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("detection_method", models.CharField(blank=True, max_length=100)),
                ("is_competitor_product", models.BooleanField(default=False)),
                ("competitor_of", models.CharField(blank=True, max_length=200)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technographics",
                        to="data_enrichment.companyenrichment",
                    ),
                ),
            ],
            options={
                "db_table": "technographic_data",
            },
        ),
        migrations.AddIndex(
            model_name="enrichmentprofile",
            index=models.Index(fields=["email"], name="enrichment__email_9276c9_idx"),
        ),
        migrations.AddIndex(
            model_name="enrichmentprofile",
            index=models.Index(fields=["domain"], name="enrichment__domain_dbf80d_idx"),
        ),
        migrations.AddIndex(
            model_name="enrichmentprofile",
            index=models.Index(fields=["status"], name="enrichment__status_b14441_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="socialprofile",
            unique_together={("enrichment_profile", "platform")},
        ),
        migrations.AlterUniqueTogether(
            name="technographicdata",
            unique_together={("company", "technology_name")},
        ),
    ]
