# Generated by Django 5.2.7 on 2026-01-24 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contact_management",
            "0003_alter_contact_assigned_to_alter_contact_created_by",
        ),
        ("data_enrichment", "0001_initial"),
        ("lead_management", "0003_alter_lead_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrichmentactivity",
            name="company",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="data_enrichment.companyenrichment",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enrichmentactivity",
            name="enrichment_profile",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="data_enrichment.enrichmentprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enrichmentprofile",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrichment_profile",
                to="contact_management.contact",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enrichmentprofile",
            name="lead",
            field=models.OneToOneField(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrichment_profile",
                to="lead_management.lead",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="intentsignal",
            name="company",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intent_signals",
                to="data_enrichment.companyenrichment",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="intentsignal",
            name="enrichment_profile",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intent_signals",
                to="data_enrichment.enrichmentprofile",
            ),
            preserve_default=False,
        ),
    ]
