# Generated by Django 5.2.7 on 2026-01-24 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmotionalState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("calm", "Calm"),
                            ("focused", "Focused"),
                            ("stressed", "Stressed"),
                            ("excited", "Excited"),
                            ("fatigued", "Fatigued"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confidence", models.FloatField()),
                ("metrics", models.JSONField(default=dict)),
                ("context", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emotional_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SentimentDrivenAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("action_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("was_executed", models.BooleanField(default=False)),
                ("user_feedback", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emotional_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurological_feedback.emotionalstate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WearableDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("eeg_headband", "EEG Headband"),
                            ("smart_watch", "Smart Watch"),
                            ("fitness_tracker", "Fitness Tracker"),
                        ],
                        max_length=100,
                    ),
                ),
                ("device_id", models.CharField(max_length=255, unique=True)),
                ("is_connected", models.BooleanField(default=False)),
                ("last_sync", models.DateTimeField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wearable_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="emotionalstate",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="neurological_feedback.wearabledevice",
            ),
        ),
        migrations.AddIndex(
            model_name="emotionalstate",
            index=models.Index(
                fields=["user", "-timestamp"], name="neurologica_user_id_79715a_idx"
            ),
        ),
    ]
