# Generated by Django 5.2.7 on 2026-01-24 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiofeedbackProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("baseline_heart_rate", models.IntegerField(blank=True)),
                ("baseline_stress_level", models.FloatField(blank=True)),
                ("preferences", models.JSONField(default=dict)),
                ("calibrated", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biofeedback_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalizationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("condition", models.JSONField(default=dict)),
                ("action", models.JSONField(default=dict)),
                ("priority", models.IntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("activation_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="biofeedback_personalization.biofeedbackprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BiometricReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("reading_type", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                ("context", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="biofeedback_personalization.biofeedbackprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["profile", "-timestamp"],
                        name="biofeedback_profile_d4db59_idx",
                    )
                ],
            },
        ),
    ]
