# Generated by Django 5.2.8 on 2025-11-12 04:14

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import document_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact_management", "0002_initial"),
        ("lead_management", "0002_initial"),
        ("opportunity_management", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("contract", "Contract"),
                            ("proposal", "Proposal"),
                            ("invoice", "Invoice"),
                            ("presentation", "Presentation"),
                            ("report", "Report"),
                            ("email", "Email"),
                            ("agreement", "Agreement"),
                            ("identification", "Identification"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=document_management.models.document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                    "txt",
                                    "csv",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                ]
                            )
                        ],
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("mime_type", models.CharField(max_length=100)),
                ("version", models.IntegerField(default=1)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(blank=True, help_text="Text extracted via OCR"),
                ),
                ("ocr_processed", models.BooleanField(default=False)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("download_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="contact_management.contact",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="lead_management.lead",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="opportunity_management.opportunity",
                    ),
                ),
                (
                    "parent_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="document_management.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "crm_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="document_management.document",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Approval",
                "verbose_name_plural": "Document Approvals",
                "db_table": "crm_document_approvals",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField()),
                ("page_number", models.IntegerField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="document_management.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Comment",
                "verbose_name_plural": "Document Comments",
                "db_table": "crm_document_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shared_with_email", models.EmailField(max_length=254)),
                ("access_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("can_download", models.BooleanField(default=True)),
                ("can_view", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True)),
                ("view_count", models.IntegerField(default=0)),
                ("download_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True)),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="document_management.document",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Share",
                "verbose_name_plural": "Document Shares",
                "db_table": "crm_document_shares",
                "ordering": ["-shared_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("proposal", "Proposal"),
                            ("contract", "Contract"),
                            ("quote", "Quote"),
                            ("invoice", "Invoice"),
                            ("agreement", "Agreement"),
                            ("letter", "Letter"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="document_templates/")),
                (
                    "variables",
                    models.JSONField(
                        default=list,
                        help_text="List of variables: ['client_name', 'amount', 'date', etc.]",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, upload_to="template_thumbnails/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Template",
                "verbose_name_plural": "Document Templates",
                "db_table": "crm_document_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["category", "uploaded_at"],
                name="crm_documen_categor_3b2383_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["lead"], name="crm_documen_lead_id_73a825_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["contact"], name="crm_documen_contact_ba44ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["opportunity"], name="crm_documen_opportu_325403_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["uploaded_by"], name="crm_documen_uploade_55c760_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentapproval",
            unique_together={("document", "approver")},
        ),
    ]
