# Generated by Django 5.2.8 on 2025-11-29 12:03

import django.core.validators
from django.db import migrations, models

import document_management.models


class Migration(migrations.Migration):

    dependencies = [
        ("document_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                upload_to=document_management.models.document_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "ppt",
                            "pptx",
                            "txt",
                            "csv",
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                        ]
                    ),
                    document_management.models.validate_file_content,
                ],
            ),
        ),
    ]
