# Generated by Django 5.2.7 on 2026-01-24 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIBiasDetection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("detection_date", models.DateTimeField(auto_now_add=True)),
                (
                    "bias_type",
                    models.CharField(
                        choices=[
                            ("demographic", "Demographic Bias"),
                            ("geographic", "Geographic Bias"),
                            ("temporal", "Temporal Bias"),
                            ("confirmation", "Confirmation Bias"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("affected_groups", models.JSONField(default=list)),
                ("confidence_score", models.FloatField()),
                ("mitigation_recommendations", models.JSONField(default=list)),
                ("is_resolved", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-detection_date"],
            },
        ),
        migrations.CreateModel(
            name="AIDecisionAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("decision_type", models.CharField(max_length=100)),
                ("input_data", models.JSONField(default=dict)),
                ("output", models.JSONField(default=dict)),
                ("explanation", models.TextField()),
                ("confidence_score", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("flagged_for_review", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "-timestamp"],
                        name="ethical_ai__model_n_be5e9d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EthicsConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("fairness_threshold", models.FloatField(default=0.8)),
                ("bias_sensitivity", models.FloatField(default=0.5)),
                (
                    "explanation_detail_level",
                    models.CharField(default="medium", max_length=20),
                ),
                ("auto_flag_threshold", models.FloatField(default=0.7)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ethics_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "model_name")},
            },
        ),
    ]
