# Generated by Django 5.2.7 on 2025-10-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('lead_source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('email_campaign', 'Email Campaign'), ('cold_call', 'Cold Call'), ('trade_show', 'Trade Show'), ('advertisement', 'Advertisement'), ('other', 'Other')], default='website', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('lead_score', models.IntegerField(default=0)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('probability', models.IntegerField(default=0)),
                ('last_contact_date', models.DateTimeField(blank=True)),
                ('next_follow_up', models.DateTimeField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_at', models.DateTimeField(blank=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'crm_leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('task', 'Task'), ('status_change', 'Status Change')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Activity',
                'verbose_name_plural': 'Lead Activities',
                'db_table': 'crm_lead_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('criteria', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead Assignment Rule',
                'verbose_name_plural': 'Lead Assignment Rules',
                'db_table': 'crm_lead_assignment_rules',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('conversion_notes', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Conversion',
                'verbose_name_plural': 'Lead Conversions',
                'db_table': 'crm_lead_conversions',
            },
        ),
    ]
