# Generated by Django 5.2.8 on 2025-11-12 06:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lead_management", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualificationCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("mql", "Marketing Qualified Lead"),
                            ("sql", "Sales Qualified Lead"),
                            ("opportunity", "Opportunity"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "minimum_score",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "required_fields",
                    models.JSONField(
                        default=list, help_text="List of required field names"
                    ),
                ),
                (
                    "required_actions",
                    models.JSONField(
                        default=list,
                        help_text="List of required actions (e.g., ['email_opened', 'form_submitted'])",
                    ),
                ),
                (
                    "time_constraint_days",
                    models.IntegerField(
                        blank=True, help_text="Days since lead creation"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lead_qualification_criteria",
                "ordering": ["stage", "minimum_score"],
                "indexes": [
                    models.Index(
                        fields=["stage", "is_active"],
                        name="lead_qualif_stage_7caec2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QualificationWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("score_threshold", "Score Threshold Reached"),
                            ("stage_change", "Stage Changed"),
                            ("field_update", "Field Updated"),
                            ("time_based", "Time-Based"),
                            ("manual", "Manual Trigger"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "trigger_config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration for trigger (e.g., {'score': 70})",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("assign_owner", "Assign Owner"),
                            ("change_status", "Change Status"),
                            ("send_email", "Send Email"),
                            ("create_task", "Create Task"),
                            ("update_field", "Update Field"),
                            ("send_notification", "Send Notification"),
                            ("move_to_stage", "Move to Stage"),
                            ("add_to_campaign", "Add to Campaign"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action_config",
                    models.JSONField(
                        default=dict, help_text="Configuration for action"
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=list, help_text="Additional conditions to check"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("execution_count", models.IntegerField(default=0)),
                ("last_executed_at", models.DateTimeField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflows_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lead_qualification_workflow",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScoringRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("demographic", "Demographic"),
                            ("behavioral", "Behavioral"),
                            ("firmographic", "Firmographic"),
                            ("engagement", "Engagement"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Field to evaluate (e.g., 'company_size', 'industry')",
                        max_length=100,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("equals", "Equals"),
                            ("not_equals", "Not Equals"),
                            ("contains", "Contains"),
                            ("not_contains", "Does Not Contain"),
                            ("greater_than", "Greater Than"),
                            ("less_than", "Less Than"),
                            ("in_list", "In List"),
                            ("not_in_list", "Not In List"),
                            ("between", "Between"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Value to compare against (JSON for complex values)"
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority rules evaluated first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scoring_rules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lead_scoring_rule",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("trigger_data", models.JSONField(default=dict)),
                ("result_data", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_executions",
                        to="lead_management.lead",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="lead_qualification.qualificationworkflow",
                    ),
                ),
            ],
            options={
                "db_table": "lead_workflow_execution",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadEnrichmentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("clearbit", "Clearbit"),
                            ("hunter", "Hunter.io"),
                            ("linkedin", "LinkedIn"),
                            ("zoominfo", "ZoomInfo"),
                            ("manual", "Manual Entry"),
                            ("api", "API Integration"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("company_size", models.CharField(blank=True, max_length=50)),
                ("company_revenue", models.CharField(blank=True, max_length=50)),
                ("company_industry", models.CharField(blank=True, max_length=100)),
                ("company_location", models.CharField(blank=True, max_length=200)),
                ("job_title", models.CharField(blank=True, max_length=200)),
                ("job_level", models.CharField(blank=True, max_length=50)),
                ("social_profiles", models.JSONField(default=dict)),
                ("technologies", models.JSONField(default=list)),
                ("enriched_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_data",
                        to="lead_management.lead",
                    ),
                ),
            ],
            options={
                "db_table": "lead_enrichment_data",
                "ordering": ["-enriched_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "-enriched_at"],
                        name="lead_enrich_lead_id_c80dfb_idx",
                    ),
                    models.Index(
                        fields=["source"], name="lead_enrich_source_ad7cea_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeadScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("previous_score", models.IntegerField(blank=True)),
                (
                    "score_breakdown",
                    models.JSONField(default=dict, help_text="Points by category"),
                ),
                ("qualification_stage", models.CharField(blank=True, max_length=50)),
                ("demographic_score", models.IntegerField(default=0)),
                ("behavioral_score", models.IntegerField(default=0)),
                ("firmographic_score", models.IntegerField(default=0)),
                ("engagement_score", models.IntegerField(default=0)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="lead_management.lead",
                    ),
                ),
            ],
            options={
                "db_table": "lead_score_history",
                "ordering": ["-calculated_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "-calculated_at"],
                        name="lead_score__lead_id_9772fa_idx",
                    ),
                    models.Index(fields=["score"], name="lead_score__score_8c498f_idx"),
                    models.Index(
                        fields=["qualification_stage"],
                        name="lead_score__qualifi_5902c0_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="qualificationworkflow",
            index=models.Index(
                fields=["trigger_type", "is_active"],
                name="lead_qualif_trigger_852ab5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="qualificationworkflow",
            index=models.Index(
                fields=["priority"], name="lead_qualif_priorit_457cb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scoringrule",
            index=models.Index(
                fields=["rule_type", "is_active"], name="lead_scorin_rule_ty_a4f6ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scoringrule",
            index=models.Index(
                fields=["priority"], name="lead_scorin_priorit_c73ac6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["workflow", "status"], name="lead_workfl_workflo_3b0d3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["lead", "-started_at"], name="lead_workfl_lead_id_b55471_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["status", "-started_at"], name="lead_workfl_status_dec77a_idx"
            ),
        ),
    ]
