# Generated by Django 5.2.7 on 2026-01-24 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication_management", "0002_alter_emailcampaign_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="communication_management.emailtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communication_email_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
