# Generated by Django 5.2.7 on 2025-11-23 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("activity", "Activity"),
                            ("quality", "Quality"),
                            ("collaboration", "Collaboration"),
                            ("milestone", "Milestone"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=20,
                    ),
                ),
                (
                    "criteria_type",
                    models.CharField(
                        choices=[
                            ("deals_won", "Deals Won"),
                            ("revenue_target", "Revenue Target"),
                            ("leads_converted", "Leads Converted"),
                            ("tasks_completed", "Tasks Completed"),
                            ("streak_days", "Streak Days"),
                            ("perfect_week", "Perfect Week"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "criteria_value",
                    models.IntegerField(help_text="Target value to achieve"),
                ),
                ("points", models.IntegerField(default=10)),
                (
                    "badge_icon",
                    models.CharField(
                        blank=True, help_text="Icon name or emoji", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_repeatable",
                    models.BooleanField(
                        default=False, help_text="Can be earned multiple times"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "ordering": ["category", "difficulty", "name"],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("total_points", "Total Points"),
                            ("deals_won", "Deals Won"),
                            ("revenue_generated", "Revenue Generated"),
                            ("leads_converted", "Leads Converted"),
                            ("tasks_completed", "Tasks Completed"),
                            ("achievements_earned", "Achievements Earned"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("all_time", "All Time"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "display_count",
                    models.IntegerField(
                        default=10, help_text="Number of top users to show"
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Leaderboard",
                "verbose_name_plural": "Leaderboards",
                "ordering": ["period", "name"],
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("team", "Team")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                (
                    "goal_metric",
                    models.CharField(
                        help_text="e.g., deals_won, revenue", max_length=100
                    ),
                ),
                ("goal_value", models.FloatField()),
                ("reward_points", models.IntegerField(default=100)),
                ("reward_description", models.TextField(blank=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Challenge",
                "verbose_name_plural": "Challenges",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="UserPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("sales_points", models.IntegerField(default=0)),
                ("activity_points", models.IntegerField(default=0)),
                ("quality_points", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("level_name", models.CharField(default="Beginner", max_length=100)),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0, help_text="Days of consecutive activity"
                    ),
                ),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Points",
                "verbose_name_plural": "User Points",
            },
        ),
        migrations.CreateModel(
            name="ChallengeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_value", models.FloatField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("rank", models.IntegerField(blank=True, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="gamification.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Challenge Progress",
                "verbose_name_plural": "Challenge Progress",
                "ordering": ["-current_value"],
                "unique_together": {("challenge", "user")},
            },
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earned", "Earned"),
                            ("bonus", "Bonus"),
                            ("penalty", "Penalty"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points", models.IntegerField()),
                ("category", models.CharField(default="activity", max_length=50)),
                ("reason", models.CharField(max_length=255)),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'lead', 'opportunity'",
                        max_length=50,
                    ),
                ),
                ("reference_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Point Transaction",
                "verbose_name_plural": "Point Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="gamificatio_user_id_b86e52_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                ("progress_value", models.IntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Achievement",
                "verbose_name_plural": "User Achievements",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "achievement", "earned_at")},
            },
        ),
    ]
