# Generated by Django 5.2.8 on 2025-11-12 04:14

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "path",
                    models.CharField(
                        help_text="API path (e.g., /custom/my-endpoint)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        default="POST",
                        max_length=10,
                    ),
                ),
                (
                    "handler_type",
                    models.CharField(
                        choices=[
                            ("webhook", "Webhook"),
                            ("function", "Python Function"),
                        ],
                        default="webhook",
                        max_length=20,
                    ),
                ),
                ("handler_url", models.URLField(blank=True)),
                (
                    "handler_code",
                    models.TextField(blank=True, help_text="Python code to execute"),
                ),
                ("requires_auth", models.BooleanField(default=True)),
                (
                    "allowed_roles",
                    models.JSONField(
                        default=list,
                        help_text="List of roles allowed to access this endpoint",
                    ),
                ),
                (
                    "rate_limit",
                    models.IntegerField(default=100, help_text="Max requests per hour"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("total_calls", models.IntegerField(default=0)),
                ("successful_calls", models.IntegerField(default=0)),
                ("failed_calls", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Endpoint",
                "verbose_name_plural": "API Endpoints",
                "db_table": "crm_api_endpoints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThirdPartyIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("slack", "Slack"),
                            ("microsoft_teams", "Microsoft Teams"),
                            ("google_calendar", "Google Calendar"),
                            ("zoom", "Zoom"),
                            ("salesforce", "Salesforce"),
                            ("hubspot", "HubSpot"),
                            ("mailchimp", "Mailchimp"),
                            ("zapier", "Zapier"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("api_secret", models.CharField(blank=True, max_length=255)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Provider-specific configuration"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hub_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Third Party Integration",
                "verbose_name_plural": "Third Party Integrations",
                "db_table": "crm_hub_integrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "url",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list, help_text="List of events to trigger webhook"
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        help_text="Secret key for HMAC signature verification",
                        max_length=64,
                    ),
                ),
                (
                    "custom_headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom HTTP headers to include",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("max_retries", models.IntegerField(default=3)),
                (
                    "retry_delay",
                    models.IntegerField(
                        default=60, help_text="Delay in seconds between retries"
                    ),
                ),
                ("total_deliveries", models.IntegerField(default=0)),
                ("successful_deliveries", models.IntegerField(default=0)),
                ("failed_deliveries", models.IntegerField(default=0)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
                "db_table": "crm_webhooks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("sync", "Sync"),
                            ("send", "Send"),
                            ("receive", "Receive"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("request_data", models.JSONField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="integration_hub.thirdpartyintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration Log",
                "verbose_name_plural": "Integration Logs",
                "db_table": "crm_integration_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["integration", "created_at"],
                        name="crm_integra_integra_edecdb_idx",
                    ),
                    models.Index(
                        fields=["action", "success"],
                        name="crm_integra_action_53dce0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("attempts", models.IntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="integration_hub.webhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Delivery",
                "verbose_name_plural": "Webhook Deliveries",
                "db_table": "crm_webhook_deliveries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["webhook", "status"],
                        name="crm_webhook_webhook_82fe57_idx",
                    ),
                    models.Index(
                        fields=["event", "created_at"],
                        name="crm_webhook_event_e02901_idx",
                    ),
                ],
            },
        ),
    ]
