# Generated by Django 6.0 on 2025-12-30 17:42

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("opportunity_management", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("website", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("strengths", models.JSONField(default=list)),
                ("weaknesses", models.JSONField(default=list)),
                ("pricing_info", models.TextField(blank=True)),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "market_share",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("deals_won_against", models.IntegerField(default=0)),
                ("deals_lost_to", models.IntegerField(default=0)),
                (
                    "differentiators",
                    models.JSONField(default=list, help_text="Our advantages"),
                ),
                ("objection_handlers", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "competitors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DealRiskAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("stale_deal", "Stale Deal - No Activity"),
                            ("slipping_close", "Close Date Slipping"),
                            ("engagement_drop", "Engagement Dropped"),
                            ("competitor_threat", "Competitor Threat"),
                            ("stakeholder_change", "Stakeholder Change"),
                            ("budget_concern", "Budget Concerns"),
                            ("timeline_risk", "Timeline at Risk"),
                            ("champion_left", "Champion Left Company"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("recommended_action", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_alerts",
                        to="opportunity_management.opportunity",
                    ),
                ),
            ],
            options={
                "db_table": "deal_risk_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DealScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        help_text="Overall deal health score 0-100",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "win_probability",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(
                        default=list, help_text="List of identified risk factors"
                    ),
                ),
                ("engagement_score", models.IntegerField(default=0)),
                ("timing_score", models.IntegerField(default=0)),
                ("stakeholder_score", models.IntegerField(default=0)),
                ("activity_score", models.IntegerField(default=0)),
                ("competitive_score", models.IntegerField(default=0)),
                ("strengths", models.JSONField(default=list)),
                ("weaknesses", models.JSONField(default=list)),
                ("recommended_actions", models.JSONField(default=list)),
                ("score_trend", models.CharField(default="stable", max_length=20)),
                ("previous_score", models.IntegerField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_score",
                        to="opportunity_management.opportunity",
                    ),
                ),
            ],
            options={
                "db_table": "deal_scores",
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="DealVelocity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_stage", models.CharField(max_length=50)),
                ("to_stage", models.CharField(max_length=50)),
                (
                    "transition_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "days_in_stage",
                    models.IntegerField(help_text="Days spent in previous stage"),
                ),
                (
                    "avg_days_for_stage",
                    models.IntegerField(
                        help_text="Average days in this stage", null=True
                    ),
                ),
                ("is_on_track", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="velocity_records",
                        to="opportunity_management.opportunity",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "deal_velocity",
                "ordering": ["-transition_date"],
            },
        ),
        migrations.CreateModel(
            name="RevenueForecast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("forecast_date", models.DateField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("team", models.CharField(blank=True, max_length=100)),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("commit", "Commit"),
                            ("best_case", "Best Case"),
                            ("pipeline", "Pipeline"),
                            ("ai_predicted", "AI Predicted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "ai_adjustment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("adjustment_reasons", models.JSONField(default=list)),
                (
                    "closed_won",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "expected_closes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "at_risk_deals",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "actual_amount",
                    models.DecimalField(decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "accuracy_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "revenue_forecasts",
                "ordering": ["-forecast_date", "-period_start"],
            },
        ),
        migrations.CreateModel(
            name="DealCompetitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actively Competing"),
                            ("eliminated", "Eliminated"),
                            ("won", "We Won"),
                            ("lost", "Lost to Them"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("known_pricing", models.TextField(blank=True)),
                ("strengths_in_deal", models.JSONField(default=list)),
                ("weaknesses_in_deal", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="revenue_intelligence.competitor",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="opportunity_management.opportunity",
                    ),
                ),
            ],
            options={
                "db_table": "deal_competitors",
                "unique_together": {("opportunity", "competitor")},
            },
        ),
        migrations.CreateModel(
            name="PipelineSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_date", models.DateField(default=django.utils.timezone.now)),
                ("team", models.CharField(blank=True, max_length=100)),
                (
                    "total_pipeline",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "weighted_pipeline",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("deal_count", models.IntegerField()),
                ("stage_breakdown", models.JSONField(default=dict)),
                (
                    "new_pipeline",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "moved_forward",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "moved_backward",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "closed_won",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "closed_lost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "avg_deal_size",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("avg_days_to_close", models.IntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pipeline_snapshots",
                "ordering": ["-snapshot_date"],
                "unique_together": {("snapshot_date", "user")},
            },
        ),
        migrations.CreateModel(
            name="RevenueTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue"),
                            ("deals", "Deal Count"),
                            ("new_business", "New Business"),
                            ("expansion", "Expansion/Upsell"),
                            ("renewal", "Renewals"),
                        ],
                        default="revenue",
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "stretch_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "achieved_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "pipeline_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "weighted_pipeline",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "revenue_targets",
                "ordering": ["-start_date"],
                "unique_together": {("user", "target_type", "period", "start_date")},
            },
        ),
    ]
