# Generated by Django 5.2.7 on 2025-11-07 13:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key_hash", models.CharField(max_length=128, unique=True)),
                ("permissions", models.JSONField(default=list)),
                ("rate_limit", models.IntegerField(default=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "crm_api_keys",
            },
        ),
        migrations.CreateModel(
            name="DataBackup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Backup"),
                            ("incremental", "Incremental"),
                            ("differential", "Differential"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Backup",
                "verbose_name_plural": "Data Backups",
                "db_table": "crm_data_backups",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Service"),
                            ("calendar", "Calendar"),
                            ("telephony", "Phone System"),
                            ("accounting", "Accounting Software"),
                            ("marketing", "Marketing Platform"),
                            ("social", "Social Media"),
                            ("analytics", "Analytics Platform"),
                            ("storage", "Cloud Storage"),
                        ],
                        max_length=30,
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("configuration", models.JSONField(default=dict)),
                ("credentials", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("configuring", "Configuring"),
                        ],
                        default="configuring",
                        max_length=20,
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("sync_frequency", models.IntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
                "db_table": "crm_integrations",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject_template", models.CharField(blank=True, max_length=500)),
                ("body_template", models.TextField()),
                ("variables", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "crm_notification_templates",
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField()),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("integration", "Integration"),
                            ("business", "Business Rules"),
                            ("ui", "User Interface"),
                            ("notification", "Notifications"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_encrypted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
                "db_table": "crm_system_config",
            },
        ),
        migrations.CreateModel(
            name="SystemHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("database", "Database"),
                            ("cache", "Cache"),
                            ("email", "Email Service"),
                            ("storage", "File Storage"),
                            ("api", "External API"),
                            ("queue", "Task Queue"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("down", "Down"),
                        ],
                        max_length=20,
                    ),
                ),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("metrics", models.JSONField(default=dict)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "System Health Check",
                "verbose_name_plural": "System Health Checks",
                "db_table": "crm_system_health",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["component", "checked_at"],
                        name="crm_system__compone_e0eafe_idx",
                    ),
                    models.Index(
                        fields=["status", "checked_at"],
                        name="crm_system__status_2ae001_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("record_created", "Record Created"),
                            ("record_updated", "Record Updated"),
                            ("field_changed", "Field Changed"),
                            ("time_based", "Time Based"),
                            ("email_received", "Email Received"),
                        ],
                        max_length=30,
                    ),
                ),
                ("trigger_conditions", models.JSONField(default=dict)),
                ("actions", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("draft", "Draft"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
                "db_table": "crm_workflows",
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trigger_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("steps_completed", models.IntegerField(default=0)),
                ("total_steps", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("execution_log", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="core.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Execution",
                "verbose_name_plural": "Workflow Executions",
                "db_table": "crm_workflow_executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("resource", models.CharField(blank=True, max_length=200, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="core_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "crm_core_audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="crm_audit_l_user_id_2742a6_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="crm_audit_l_action_a339c3_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "timestamp"],
                        name="crm_audit_l_risk_le_6a80fb_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="crm_audit_l_ip_addr_c32b41_idx",
                    ),
                ],
            },
        ),
    ]
