# Generated by Django 5.2.7 on 2025-11-23 05:44

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0002_dashboard_dataimportlog_emailcampaign_emailclick_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.CharField(max_length=100, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("track_creates", models.BooleanField(default=True)),
                ("track_updates", models.BooleanField(default=True)),
                ("track_deletes", models.BooleanField(default=True)),
                (
                    "track_views",
                    models.BooleanField(
                        default=False, help_text="Track read operations"
                    ),
                ),
                (
                    "excluded_fields",
                    models.JSONField(
                        default=list, help_text="Fields to not track changes for"
                    ),
                ),
                (
                    "retention_days",
                    models.IntegerField(
                        default=365, help_text="Days to keep audit records"
                    ),
                ),
                ("enable_snapshots", models.BooleanField(default=False)),
                (
                    "snapshot_frequency_days",
                    models.IntegerField(
                        default=7, help_text="Days between automatic snapshots"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Audit Configuration",
                "verbose_name_plural": "Audit Configurations",
                "db_table": "crm_audit_configuration",
            },
        ),
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        help_text="Store email in case user is deleted", max_length=254
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                (
                    "object_repr",
                    models.CharField(
                        help_text="String representation of object", max_length=500
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("view", "Viewed"),
                            ("export", "Exported"),
                            ("import", "Imported"),
                            ("share", "Shared"),
                            ("permission_change", "Permission Changed"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the change"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(default=dict, help_text="Field-by-field changes"),
                ),
                (
                    "old_values",
                    models.JSONField(default=dict, help_text="Previous values"),
                ),
                ("new_values", models.JSONField(default=dict, help_text="New values")),
                ("ip_address", models.GenericIPAddressField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Group related changes"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_trails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Trail",
                "verbose_name_plural": "Audit Trails",
                "db_table": "crm_audit_trail",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Text Area"),
                            ("number", "Number"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("datetime", "Date & Time"),
                            ("email", "Email"),
                            ("url", "URL"),
                            ("phone", "Phone"),
                            ("select", "Dropdown"),
                            ("multiselect", "Multi-Select"),
                            ("radio", "Radio Buttons"),
                            ("checkbox", "Checkboxes"),
                            ("file", "File Upload"),
                        ],
                        max_length=20,
                    ),
                ),
                ("help_text", models.TextField(blank=True)),
                ("placeholder", models.CharField(blank=True, max_length=200)),
                ("is_required", models.BooleanField(default=False)),
                ("min_length", models.IntegerField(blank=True)),
                ("max_length", models.IntegerField(blank=True)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20
                    ),
                ),
                ("regex_pattern", models.CharField(blank=True, max_length=500)),
                ("regex_error_message", models.CharField(blank=True, max_length=200)),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text="List of options for select fields: [{'value': 'opt1', 'label': 'Option 1'}, ...]",
                    ),
                ),
                ("default_value", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_searchable", models.BooleanField(default=False)),
                ("is_filterable", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("visible_to_roles", models.JSONField(blank=True, default=list)),
                ("editable_by_roles", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_custom_fields",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["content_type", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_collapsible", models.BooleanField(default=True)),
                ("is_collapsed_by_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["content_type", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "custom_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="core.customfield",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_memberships",
                        to="core.customfieldgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("value_text", models.TextField(blank=True)),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20
                    ),
                ),
                ("value_boolean", models.BooleanField(blank=True)),
                ("value_date", models.DateField(blank=True)),
                ("value_datetime", models.DateTimeField(blank=True)),
                ("value_json", models.JSONField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "custom_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="core.customfield",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("metric", "Metric Card"),
                            ("chart_line", "Line Chart"),
                            ("chart_bar", "Bar Chart"),
                            ("chart_pie", "Pie Chart"),
                            ("chart_area", "Area Chart"),
                            ("table", "Data Table"),
                            ("funnel", "Funnel Chart"),
                            ("goal", "Goal Progress"),
                            ("leaderboard", "Leaderboard"),
                            ("timeline", "Activity Timeline"),
                            ("map", "Geographic Map"),
                            ("list", "Recent Items List"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        help_text="API endpoint or data source identifier",
                        max_length=100,
                    ),
                ),
                (
                    "query_params",
                    models.JSONField(
                        default=dict, help_text="Parameters for data query"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small (1x1)"),
                            ("medium", "Medium (2x1)"),
                            ("large", "Large (2x2)"),
                            ("wide", "Wide (4x1)"),
                            ("full", "Full Width (4x2)"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("color_scheme", models.CharField(default="blue", max_length=50)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon identifier", max_length=50
                    ),
                ),
                (
                    "chart_config",
                    models.JSONField(
                        default=dict, help_text="Chart.js or similar config"
                    ),
                ),
                (
                    "value_format",
                    models.CharField(
                        default="number",
                        help_text="number, currency, percentage, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "value_prefix",
                    models.CharField(blank=True, help_text="e.g., $", max_length=10),
                ),
                (
                    "value_suffix",
                    models.CharField(blank=True, help_text="e.g., %", max_length=10),
                ),
                (
                    "refresh_interval",
                    models.IntegerField(
                        choices=[
                            (0, "Manual"),
                            (60, "1 minute"),
                            (300, "5 minutes"),
                            (900, "15 minutes"),
                            (1800, "30 minutes"),
                            (3600, "1 hour"),
                        ],
                        default=300,
                    ),
                ),
                ("last_refreshed_at", models.DateTimeField(blank=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Available to all users"
                    ),
                ),
                (
                    "shared_with_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Role IDs that can view this widget",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_widgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_widgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Widget",
                "verbose_name_plural": "Dashboard Widgets",
                "db_table": "crm_dashboard_widgets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                (
                    "snapshot_data",
                    models.JSONField(
                        help_text="Complete object data at this point in time"
                    ),
                ),
                ("version", models.IntegerField(default=1, help_text="Version number")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Optional note about this snapshot"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Snapshot",
                "verbose_name_plural": "Data Snapshots",
                "db_table": "crm_data_snapshots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                ("field_name", models.CharField(max_length=100)),
                ("field_label", models.CharField(blank=True, max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                (
                    "old_value_display",
                    models.TextField(blank=True, help_text="Human-readable old value"),
                ),
                (
                    "new_value_display",
                    models.TextField(blank=True, help_text="Human-readable new value"),
                ),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "audit_trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_changes",
                        to="core.audittrail",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field History",
                "verbose_name_plural": "Field Histories",
                "db_table": "crm_field_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="UserDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "layout_config",
                    models.JSONField(
                        default=dict, help_text="Grid layout configuration"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Dashboard",
                "verbose_name_plural": "User Dashboards",
                "db_table": "crm_user_dashboards",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidgetPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row", models.IntegerField(default=0)),
                ("column", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=2, help_text="Grid columns")),
                ("height", models.IntegerField(default=1, help_text="Grid rows")),
                ("order", models.IntegerField(default=0)),
                ("custom_title", models.CharField(blank=True, max_length=200)),
                ("custom_query_params", models.JSONField(blank=True, default=dict)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.dashboardwidget",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widget_placements",
                        to="core.userdashboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget Placement",
                "verbose_name_plural": "Widget Placements",
                "db_table": "crm_dashboard_widget_placements",
                "ordering": ["order", "row", "column"],
            },
        ),
        migrations.CreateModel(
            name="WidgetDataCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "query_params",
                    models.JSONField(
                        default=dict, help_text="Params used to generate this cache"
                    ),
                ),
                ("cached_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("hit_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User-specific cache",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_data",
                        to="core.dashboardwidget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget Data Cache",
                "verbose_name_plural": "Widget Data Caches",
                "db_table": "crm_widget_data_cache",
            },
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["user", "-timestamp"], name="crm_audit_t_user_id_1d80c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["content_type", "object_id", "-timestamp"],
                name="crm_audit_t_content_c97813_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["action", "-timestamp"], name="crm_audit_t_action_ec6396_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["request_id"], name="crm_audit_t_request_547e44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customfield",
            index=models.Index(
                fields=["content_type", "is_active"],
                name="core_custom_content_3a9423_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customfield",
            unique_together={("content_type", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="customfieldgroupmembership",
            unique_together={("group", "custom_field")},
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="core_custom_content_d2b966_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["custom_field"], name="core_custom_custom__5ae1d7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customfieldvalue",
            unique_together={("custom_field", "content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="datasnapshot",
            index=models.Index(
                fields=["content_type", "object_id", "-created_at"],
                name="crm_data_sn_content_634bea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldhistory",
            index=models.Index(
                fields=["content_type", "object_id", "field_name", "-changed_at"],
                name="crm_field_h_content_32b041_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userdashboard",
            unique_together={("user", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="dashboardwidgetplacement",
            unique_together={("dashboard", "widget")},
        ),
        migrations.AddIndex(
            model_name="widgetdatacache",
            index=models.Index(
                fields=["widget", "user", "expires_at"],
                name="crm_widget__widget__3a915b_idx",
            ),
        ),
    ]
