# Generated by Django 6.0 on 2025-12-28 08:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0003_auditconfiguration_audittrail_customfield_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("level", models.IntegerField(default=0)),
                ("permissions", models.JSONField(default=list)),
                (
                    "color",
                    models.CharField(
                        default="bg-gray-100 text-gray-700", max_length=50
                    ),
                ),
                ("is_system_role", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "ordering": ["-level"],
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("json", "JSON"), ("xlsx", "Excel")],
                        default="csv",
                        max_length=10,
                    ),
                ),
                ("entities", models.JSONField(default=list)),
                (
                    "date_range",
                    models.CharField(
                        choices=[
                            ("all", "All Time"),
                            ("year", "Last Year"),
                            ("quarter", "Last Quarter"),
                            ("month", "Last Month"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("include_archived", models.BooleanField(default=False)),
                ("include_deleted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Job",
                "verbose_name_plural": "Export Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(default="22:00")),
                ("quiet_hours_end", models.TimeField(default="08:00")),
                ("quiet_hours_days", models.JSONField(blank=True, default=list)),
                ("digest_enabled", models.BooleanField(default=True)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("digest_time", models.TimeField(default="09:00")),
                ("digest_include_ai", models.BooleanField(default=True)),
                ("digest_include_metrics", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="core_notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="OnboardingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_steps",
                    models.JSONField(
                        default=list, help_text="List of completed onboarding step IDs"
                    ),
                ),
                ("tour_completed", models.BooleanField(default=False)),
                ("tour_dismissed", models.BooleanField(default=False)),
                ("tour_completed_at", models.DateTimeField(blank=True, null=True)),
                ("onboarding_xp", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Progress",
                "verbose_name_plural": "Onboarding Progress",
                "db_table": "crm_onboarding_progress",
            },
        ),
        migrations.CreateModel(
            name="QuickAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("navigation", "Navigation"),
                            ("create", "Create Entity"),
                            ("workflow", "Run Workflow"),
                            ("external", "External Link"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_config", models.JSONField(default=dict)),
                ("url", models.CharField(blank=True, max_length=500)),
                ("icon", models.CharField(default="zap", max_length=50)),
                ("color", models.CharField(default="blue", max_length=20)),
                ("shortcut", models.CharField(blank=True, max_length=20)),
                ("order", models.IntegerField(default=0)),
                ("is_pinned", models.BooleanField(default=False)),
                ("use_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quick Action",
                "verbose_name_plural": "Quick Actions",
                "db_table": "crm_quick_actions",
                "ordering": ["order", "-is_pinned", "name"],
            },
        ),
        migrations.CreateModel(
            name="SmartFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("contact", "Contact"),
                            ("lead", "Lead"),
                            ("opportunity", "Opportunity"),
                            ("task", "Task"),
                            ("company", "Company"),
                        ],
                        max_length=50,
                    ),
                ),
                ("filter_config", models.JSONField(default=dict)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("use_count", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("is_shared", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Filter",
                "verbose_name_plural": "Smart Filters",
                "db_table": "crm_smart_filters",
                "ordering": ["-use_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                ("accent_color", models.CharField(default="#3b82f6", max_length=7)),
                (
                    "font_size",
                    models.IntegerField(
                        default=14,
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("compact_mode", models.BooleanField(default=False)),
                ("animations_enabled", models.BooleanField(default=True)),
                ("high_contrast", models.BooleanField(default=False)),
                (
                    "default_view",
                    models.CharField(
                        choices=[
                            ("overview", "Overview"),
                            ("pipeline", "Pipeline"),
                            ("activity", "Activity"),
                            ("analytics", "Analytics"),
                        ],
                        default="overview",
                        max_length=20,
                    ),
                ),
                ("sidebar_collapsed", models.BooleanField(default=False)),
                ("show_welcome_message", models.BooleanField(default=True)),
                ("auto_refresh_enabled", models.BooleanField(default=True)),
                (
                    "auto_refresh_interval",
                    models.IntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                ("dashboard_layout", models.JSONField(blank=True, default=dict)),
                ("share_activity_with_team", models.BooleanField(default=True)),
                ("show_online_status", models.BooleanField(default=True)),
                ("allow_mentions", models.BooleanField(default=True)),
                ("data_export_enabled", models.BooleanField(default=True)),
                ("sound_enabled", models.BooleanField(default=True)),
                (
                    "sound_volume",
                    models.IntegerField(
                        default=70,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("keyboard_shortcuts", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dashboard_layout",
                    models.JSONField(
                        default=dict,
                        help_text="Widget positions and visibility settings",
                    ),
                ),
                ("sidebar_collapsed", models.BooleanField(default=False)),
                ("theme", models.CharField(default="system", max_length=20)),
                ("accent_color", models.CharField(default="blue", max_length=20)),
                ("enable_sounds", models.BooleanField(default=True)),
                ("enable_desktop_notifications", models.BooleanField(default=True)),
                (
                    "pinned_actions",
                    models.JSONField(
                        default=list, help_text="List of pinned quick action IDs"
                    ),
                ),
                (
                    "saved_filters",
                    models.JSONField(
                        default=dict, help_text="Saved filter presets per entity type"
                    ),
                ),
                (
                    "recent_items",
                    models.JSONField(
                        default=list,
                        help_text="Recently accessed items for quick access",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "db_table": "crm_user_preferences",
            },
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("action", "Action Required"),
                            ("insight", "Insight"),
                            ("warning", "Warning"),
                            ("opportunity", "Opportunity"),
                            ("tip", "Tip"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                ("action_label", models.CharField(blank=True, max_length=100)),
                ("action_url", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dismissed", "Dismissed"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("dismissable", models.BooleanField(default=True)),
                ("confidence_score", models.FloatField(default=0.8)),
                (
                    "reasoning",
                    models.TextField(
                        blank=True, help_text="AI reasoning for this recommendation"
                    ),
                ),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Recommendation",
                "verbose_name_plural": "AI Recommendations",
                "db_table": "crm_ai_recommendations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-created_at"],
                        name="crm_ai_reco_user_id_d4200d_idx",
                    ),
                    models.Index(
                        fields=["recommendation_type", "-created_at"],
                        name="crm_ai_reco_recomme_ea0d62_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationTypeSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("deal_stage_change", "Deal Stage Changes"),
                            ("deal_won", "Deal Won"),
                            ("deal_lost", "Deal Lost"),
                            ("deal_assigned", "Deal Assigned"),
                            ("task_due_soon", "Task Due Soon"),
                            ("task_overdue", "Task Overdue"),
                            ("task_assigned", "Task Assigned"),
                            ("mention", "Mentions"),
                            ("comment", "Comments"),
                            ("team_activity", "Team Activity"),
                            ("system_updates", "System Updates"),
                            ("security_alerts", "Security Alerts"),
                            ("ai_recommendations", "AI Recommendations"),
                            ("ai_insights", "AI Insights"),
                        ],
                        max_length=50,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="instant",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "notification_preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_settings",
                        to="core.notificationpreference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Type Setting",
                "verbose_name_plural": "Notification Type Settings",
                "unique_together": {("notification_preference", "notification_type")},
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("results_count", models.IntegerField(default=0)),
                ("clicked_result_type", models.CharField(blank=True, max_length=50)),
                ("clicked_result_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Query",
                "verbose_name_plural": "Search Queries",
                "db_table": "crm_search_queries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="crm_search__user_id_30141f_idx",
                    ),
                    models.Index(fields=["query"], name="crm_search__query_6b4f6b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "organization_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.userrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role Assignment",
                "verbose_name_plural": "User Role Assignments",
                "unique_together": {("user", "role", "team_id", "organization_id")},
            },
        ),
    ]
