# Generated by Django 6.0 on 2026-04-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_audittrail_ip_address_alter_audittrail_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingprogress",
            name="onboarding_xp",
            field=models.IntegerField(
                default=0, help_text="Experience points earned during onboarding"
            ),
        ),
    ]
